-- SPDX-License-Identifier: MIT OR Apache-2.0
--
-- The control plane's DELETE on claims_mappings (issue #113).
--
-- 0159 created the table and deliberately withheld this grant, saying why:
--
--     No DELETE. Removing a client's mapping is an ordinary operation this table will need, and
--     the operation does not exist yet; a privilege held by nobody is one an attacker inherits
--     for free.
--
-- The operation exists now: `ActingClaimsMappingRepo::delete`, audited as
-- `claims_mapping.delete`, behind the management API's `DELETE .../claims-mapping`.
--
-- CONTROL PLANE ONLY, which is the same split 0159 drew for INSERT and UPDATE.
--
-- Deleting a mapping restores the UNMAPPED token, and that is a change in BOTH directions:
-- claims the mapping filtered out come back to the ID token, and a claim it had PLACED in the
-- access token stops reaching one, so a resource server authorizing on it starts refusing.
-- Either way it changes the shape of every token this client is issued, and the plane that
-- mints them must not be able to do that to itself.
GRANT DELETE ON claims_mappings TO ironauth_control;
