// SPDX-License-Identifier: MIT OR Apache-2.0

//! The boot-wiring harness (issue #414): what the ASSEMBLED plane states hold.
//!
//! Before this, `crates/ironauth` had no test that observed a plane state. Its only
//! test drove a CLI subcommand as a subprocess, and both plane assemblies ended in an
//! opaque `Router`, so three silent boot-wiring failures were expressible for every
//! value both planes consume: dropping the install on the management plane, dropping it
//! on the data plane, and handing the two planes DIFFERENT values. Two of the three
//! built with zero warnings and the third was caught only incidentally, by
//! `unused_variable`.
//!
//! This suite assembles BOTH plane states from ONE config, through the REAL
//! [`assemble_planes`], against a real database and with no server and no listening
//! socket, and reads back what each plane actually holds.
//!
//! It drives [`assemble_planes`] rather than the two builders under it for a reason
//! that is the whole point of the suite: the discipline under test is that ONE capture
//! feeds BOTH planes. A harness that called the two builders itself would supply that
//! discipline by construction and then assert it, which proves nothing about the boot
//! path. Driving the one function that performs the capture makes the single carrier an
//! OBSERVED property of production code. Measured against a harness that called the two
//! builders: capturing twice with opposite ladder verdicts, handing one plane a freshly
//! built federation runtime, and swapping the capture site's two boolean arguments were
//! all green.
//!
//! The subject list is DERIVED, never written out here. It is
//! [`SHARED_CONFIG_SECTION_NAMES`] and [`SHARED_BOOT_INPUT_NAMES`], generated by the
//! same `shared_plane_inputs!` expansion that generates the install body itself;
//! [`SHARED_OBJECT_NAMES`] additionally REQUIRES an identity probe, and
//! [`SHARED_DERIVED_NAMES`] additionally requires that the subject be distinguishable
//! in EVERY run. A value declared there without a probe turns
//! [`every_declared_shared_value_has_a_probe`] red, and a probe naming a value that is
//! no longer declared turns it red too, so this suite cannot quietly stop covering a
//! shared value.
//!
//! Non-vacuity is OBSERVED, not asserted against a written constant: every probe is
//! also read off a pair of UNWIRED plane states, built by the same constructors from
//! the shipped default config with nothing installed, and the driven value must differ
//! from what those report. A written "what an uninstalled plane reports" constant can
//! agree with the state struct's real default by coincidence and then quietly stop
//! agreeing. Measured with such a constant in place: changing the states' uninstalled
//! `max_group_depth` to the driven value, or flipping the states' default
//! `signup_quarantine_enabled` to true, disarmed the guard entirely while every test
//! stayed green.
//!
//! One honest limit to record: this suite issues NO management-plane query. It proves
//! what each plane HOLDS, and (through the control-plane DSN) that the management plane
//! authenticates as the separate control credential, but it exercises none of that
//! role's grants.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::sync::Arc;
use std::time::SystemTime;

use ironauth_admin::AdminState;
use ironauth_config::{
    ADVANCED_RECOVERY_FEATURE, ADVANCED_RECOVERY_VERSION, Config, FeatureRegistry,
    SIGNUP_QUARANTINE_FEATURE, SIGNUP_QUARANTINE_VERSION,
};
use ironauth_env::{Env, ManualClock};
use ironauth_oidc::{IssuerRegistry, JwksCacheWindow, OidcState};
use ironauth_server::SiteContext;
use ironauth_store::Store;
use ironauth_store::test_support::TestDatabase;
use serde_json::{Value, json};

use super::assemble_planes;
use crate::shared_config::{
    SHARED_BOOT_INPUT_NAMES, SHARED_CONFIG_SECTION_NAMES, SHARED_DERIVED_NAMES, SHARED_OBJECT_NAMES,
};

/// The public URL the harness config sets, from which the boot path derives the ONE
/// issuer base both planes take. A reserved TLD, so nothing here could resolve.
const PUBLIC_URL: &str = "https://boot-wiring.invalid";

/// The JWKS cache window the harness config sets, in seconds. Away from the shipped
/// default (600) and inside the validated 300 to 900 range, so the clamp both planes
/// apply is a no-op and cannot mask a divergence.
const JWKS_CACHE_MAX_AGE_SECS: u64 = 900;

/// The address of the object behind an `Arc`, which is what an identity contract means:
/// the two planes hold the SAME object, not an equal one.
fn address<T>(handle: &Arc<T>) -> usize {
    Arc::as_ptr(handle).addr()
}

/// One cross-plane value's probe.
///
/// A probe says what the fixture drove the value to and how to read it back off each
/// assembled plane state. It deliberately carries no statement of what an uninstalled
/// plane would report: that is OBSERVED, off the unwired pair, so it cannot drift.
struct SharedValueProbe {
    /// The declared name, which must match a [`SHARED_CONFIG_SECTION_NAMES`] or
    /// [`SHARED_BOOT_INPUT_NAMES`] entry.
    name: &'static str,
    /// For a config SECTION: TOML driving every key of the section away from its
    /// default. Empty for everything else, whose driving lives in the base harness
    /// config because its keys sit inside tables that config already opens. Which of
    /// the two applies is checked against the declaration, not left to this field.
    non_default_toml: &'static str,
    /// What the fixture says both planes should hold.
    expected: fn(&BootFixture) -> Value,
    /// What the OIDC data plane actually holds.
    on_oidc: fn(&OidcState) -> Value,
    /// What the management plane actually holds.
    on_admin: fn(&AdminState) -> Value,
    /// For a [`SHARED_OBJECT_NAMES`] subject: the address of the object the OIDC data
    /// plane holds. The harness compares the two addresses ITSELF, so a probe cannot
    /// satisfy the identity requirement with a predicate that ignores its arguments.
    oidc_object: Option<fn(&OidcState) -> Option<usize>>,
    /// The same, on the management plane.
    admin_object: Option<fn(&AdminState) -> Option<usize>>,
}

/// The probe for every declared cross-plane value.
const PROBES: &[SharedValueProbe] = &[
    SharedValueProbe {
        name: "organizations",
        // Default max_group_depth is 8 and the ceiling is 32, so 3 differs from the
        // default and survives the clamp both installs apply.
        non_default_toml: "[organizations]\nmax_group_depth = 3\n",
        expected: |fixture| {
            serde_json::to_value(&fixture.config.organizations).expect("the section serializes")
        },
        on_oidc: |state| json!({ "max_group_depth": state.max_group_depth() }),
        on_admin: |state| json!({ "max_group_depth": state.max_group_depth() }),
        oidc_object: None,
        admin_object: None,
    },
    SharedValueProbe {
        name: "token_claims",
        // Every key away from its shipped default (4096 / 3072 / 256 / 192 /
        // roles_only), and every one inside its ceiling with each threshold at or below
        // the maximum it warns about, so `TokenClaimsConfig::clamped` (applied by both
        // installs) is a no-op and cannot mask a divergence.
        non_default_toml: "[token_claims]\n\
             access_token_max_bytes = 8192\n\
             access_token_warn_bytes = 5000\n\
             permission_claim_max_count = 300\n\
             permission_claim_warn_count = 100\n\
             permission_claim_overflow = \"pdp_required\"\n",
        expected: |fixture| {
            serde_json::to_value(&fixture.config.token_claims).expect("the section serializes")
        },
        on_oidc: |state| {
            serde_json::to_value(state.token_claims()).expect("the section serializes")
        },
        on_admin: |state| {
            serde_json::to_value(state.token_claims()).expect("the section serializes")
        },
        oidc_object: None,
        admin_object: None,
    },
    SharedValueProbe {
        name: "signup_quarantine_enabled",
        non_default_toml: "",
        expected: |fixture| json!({ "armed": fixture.ladder.signup_quarantine }),
        on_oidc: |state| json!({ "armed": state.signup_quarantine_enabled() }),
        on_admin: |state| json!({ "armed": state.signup_quarantine_enabled() }),
        oidc_object: None,
        admin_object: None,
    },
    SharedValueProbe {
        name: "advanced_recovery_enabled",
        non_default_toml: "",
        expected: |fixture| json!({ "armed": fixture.ladder.advanced_recovery }),
        on_oidc: |state| json!({ "armed": state.advanced_recovery_enabled() }),
        on_admin: |state| json!({ "armed": state.advanced_recovery_enabled() }),
        oidc_object: None,
        admin_object: None,
    },
    SharedValueProbe {
        name: "migration_hook",
        non_default_toml: "",
        expected: |_| json!({ "installed": true }),
        on_oidc: |state| json!({ "installed": state.migration_hook().is_some() }),
        on_admin: |state| json!({ "installed": state.migration_hook().is_some() }),
        oidc_object: Some(|state| state.migration_hook().map(address)),
        admin_object: Some(|state| state.migration_hook().map(address)),
    },
    SharedValueProbe {
        name: "federation_runtime",
        non_default_toml: "",
        expected: |_| json!({ "installed": true }),
        on_oidc: |state| json!({ "installed": state.federation().is_some() }),
        on_admin: |state| json!({ "installed": state.federation().is_some() }),
        oidc_object: Some(|state| state.federation().map(address)),
        admin_object: Some(|state| state.federation().map(address)),
    },
    SharedValueProbe {
        name: "issuer_base",
        non_default_toml: "",
        // Read off the fixture's own config through the one pure derivation, so the
        // expectation is what an operator's `server.public_url` means rather than a
        // restatement of what the boot path happened to compute.
        expected: |fixture| {
            let site = SiteContext::derive(&fixture.config.server).expect("the harness URL parses");
            json!({ "issuer_base": site.base_url() })
        },
        // The registry each plane reads keys through carries the base the mint stamps
        // and the base the console credential bridge enforces `iss` against. A plane
        // with no registry reports null, which differs from the driven value and fails
        // loudly rather than passing over an absence.
        on_oidc: |state| json!({ "issuer_base": state.issuers().issuer_base() }),
        on_admin: |state| {
            json!({
                "issuer_base": state
                    .shared_issuer_registry()
                    .map(|registry| registry.issuer_base()),
            })
        },
        oidc_object: None,
        admin_object: None,
    },
    SharedValueProbe {
        name: "jwks_cache",
        non_default_toml: "",
        expected: |fixture| json!({ "max_age_secs": fixture.config.oidc.jwks_cache_max_age_secs }),
        on_oidc: |state| json!({ "max_age_secs": state.issuers().cache().max_age_secs() }),
        on_admin: |state| {
            json!({
                "max_age_secs": state
                    .shared_issuer_registry()
                    .map(|registry| registry.cache().max_age_secs()),
            })
        },
        oidc_object: None,
        admin_object: None,
    },
    SharedValueProbe {
        name: "master_key",
        non_default_toml: "",
        expected: |_| json!({ "installed": true }),
        on_oidc: |state| json!({ "installed": state.store().master_key().is_some() }),
        on_admin: |state| json!({ "installed": state.store().master_key().is_some() }),
        oidc_object: Some(|state| state.store().master_key().map(address)),
        admin_object: Some(|state| state.store().master_key().map(address)),
    },
];

/// What the fixture's `[features]` table arms.
///
/// The two ladder verdicts are driven ASYMMETRICALLY across the suite's two runs, so a
/// cross-wiring between them is visible. Driving both to the same constant hides it:
/// measured, swapping the bodies of the two `install_*` methods on the management plane
/// was green while both were true.
#[derive(Debug, Clone, Copy)]
struct LadderIntent {
    /// Whether `[features]` enables and acks the signup fraud review queue.
    signup_quarantine: bool,
    /// Whether `[features]` enables and acks the advanced recovery review queue.
    advanced_recovery: bool,
}

/// One boot's worth of inputs: the config the planes are assembled from, the env seam,
/// the validated ladder, and what that ladder was meant to arm.
struct BootFixture {
    /// The ONE config both planes are assembled from.
    config: Config,
    /// The deterministic clock and entropy seam.
    env: Env,
    /// The strict feature ladder, validated exactly as the boot path validates it.
    features: FeatureRegistry,
    /// What the `[features]` table was written to arm, asserted against the ladder.
    ladder: LadderIntent,
}

/// The object keys of a JSON object value, sorted.
fn keys_of(value: &Value) -> Vec<String> {
    let mut keys: Vec<String> = value
        .as_object()
        .expect("a probe observation is a JSON object")
        .keys()
        .cloned()
        .collect();
    keys.sort();
    keys
}

/// The config the harness boots both planes from: the throwaway database and its
/// SEPARATE control-plane credential, an armed OIDC plane with the lazy-migration hook
/// and the federation runtime both on, a public URL and a cache window away from the
/// shipped defaults, an envelope master key, the `[features]` table this run's ladder
/// intent calls for, and every config-section probe's non-default section.
fn harness_config(db: &TestDatabase, ladder: LadderIntent) -> Config {
    let mut toml = format!(
        "[server]\npublic_url = \"{PUBLIC_URL}\"\n\
         [database]\nurl = \"{app}\"\n\
         master_key = \"boot-wiring-harness-master-key\"\n\
         [admin]\nbootstrap_operator_token = \"boot-wiring-harness\"\n\
         control_database_url = \"{control}\"\n\
         [oidc]\nenabled = true\n\
         jwks_cache_max_age_secs = {JWKS_CACHE_MAX_AGE_SECS}\n\
         [oidc.lazy_migration]\nenabled = true\n\
         endpoint = \"https://legacy.invalid/verify\"\n\
         [oidc.federation]\nenabled = true\n\
         [features]\n",
        app = db.app_url(),
        control = db.control_url(),
    );
    // An experimental feature is armed only by an explicit enable AND an ack at its
    // exact current version, so the ack is written from the same constant the ladder
    // checks against and cannot rot into a silently disarmed run.
    if ladder.signup_quarantine {
        writeln!(
            toml,
            "\"signup-quarantine\" = {{ enabled = true, ack = \"{SIGNUP_QUARANTINE_VERSION}\" }}"
        )
        .expect("writing to a String cannot fail");
    }
    if ladder.advanced_recovery {
        writeln!(
            toml,
            "\"advanced-recovery\" = {{ enabled = true, ack = \"{ADVANCED_RECOVERY_VERSION}\" }}"
        )
        .expect("writing to a String cannot fail");
    }
    for probe in PROBES {
        toml.push_str(probe.non_default_toml);
    }
    Config::from_toml_str(&toml, "<boot-wiring-harness>")
        .expect("the harness config is valid")
        .config
}

/// One boot's inputs, resolved exactly as `serve` resolves them.
fn fixture(db: &TestDatabase, env: &Env, ladder: LadderIntent) -> BootFixture {
    let config = harness_config(db, ladder);
    let features = FeatureRegistry::builtin();
    features
        .validate(&config)
        .expect("the harness config must pass the same feature gate the boot path applies");
    // Anchor: the `[features]` table actually armed what this run intends. Without this
    // a typo in an ack would leave both verdicts off, and the two runs would silently
    // become the same run.
    assert_eq!(
        features.is_enabled(&config, SIGNUP_QUARANTINE_FEATURE),
        ladder.signup_quarantine,
        "the harness config must arm signup-quarantine exactly as this run intends"
    );
    assert_eq!(
        features.is_enabled(&config, ADVANCED_RECOVERY_FEATURE),
        ladder.advanced_recovery,
        "the harness config must arm advanced-recovery exactly as this run intends"
    );
    BootFixture {
        config,
        env: env.clone(),
        features,
        ladder,
    }
}

/// The two plane states one boot produced, read side by side.
struct PlanePair {
    /// The OIDC data plane's mint state.
    oidc: OidcState,
    /// The management plane's state.
    admin: AdminState,
}

/// The two plane states, assembled from ONE fixture through the REAL boot path.
async fn boot_both_planes(fixture: &BootFixture) -> PlanePair {
    let planes = assemble_planes(&fixture.config, &fixture.env, &fixture.features)
        .await
        .expect("the harness config derives a valid site context");
    let oidc = planes
        .oidc
        .expect("the OIDC data plane must assemble against the throwaway database");
    let admin = planes
        .management
        .expect("the management plane must assemble against the throwaway database");
    PlanePair {
        oidc: oidc.state,
        admin,
    }
}

/// Drive ONE probe across the two assembled planes, and report whether what it drove
/// was distinguishable from what the unwired pair holds.
///
/// Distinguishability is returned rather than asserted here because a ladder verdict is
/// deliberately driven OFF in one of the two runs; the caller holds that decision.
fn observe_probe(
    probe: &SharedValueProbe,
    fixture: &BootFixture,
    wired: &PlanePair,
    unwired: &PlanePair,
) -> bool {
    let name = probe.name;
    let expected = (probe.expected)(fixture);
    let on_oidc = (probe.on_oidc)(&wired.oidc);
    let on_admin = (probe.on_admin)(&wired.admin);
    // Every key of the value must be observable on both planes, so a shared section that
    // GROWS a key fails here until the new key is installed and read back rather than
    // compared around.
    assert_eq!(
        keys_of(&on_oidc),
        keys_of(&expected),
        "the `{name}` observation on the OIDC data plane must cover exactly the keys of \
         the value it is compared against"
    );
    assert_eq!(
        keys_of(&on_admin),
        keys_of(&expected),
        "the `{name}` observation on the management plane must cover exactly the keys of \
         the value it is compared against"
    );
    assert_eq!(
        on_oidc, expected,
        "the OIDC data plane must hold the configured `{name}`, not the default"
    );
    assert_eq!(
        on_admin, expected,
        "the management plane must hold the configured `{name}`, not the default"
    );
    assert_eq!(
        on_oidc, on_admin,
        "the two planes must hold the SAME `{name}`: one bound, one operator-visible name"
    );

    // For a shared object, equal is not enough: the two planes must hold the SAME object,
    // because one writes into it and the other reads out of it, or because the value
    // exposes no bytes to compare. The comparison is done HERE, not by a probe-supplied
    // predicate, so no probe can satisfy this requirement with something that ignores its
    // arguments.
    if let (Some(read_oidc), Some(read_admin)) = (probe.oidc_object, probe.admin_object) {
        // An identity reader must READ the plane: an unwired plane holds no such object,
        // so one that answered with a constant address (the shape that would satisfy an
        // identity check while proving nothing) fails here.
        assert!(
            read_oidc(&unwired.oidc).is_none() && read_admin(&unwired.admin).is_none(),
            "the `{name}` identity readers must read the plane; an UNWIRED plane holds no \
             such object, so a reader that reports one is answering from something other \
             than the state"
        );
        let held_by_oidc = read_oidc(&wired.oidc);
        let held_by_admin = read_admin(&wired.admin);
        assert!(
            held_by_oidc.is_some(),
            "the OIDC data plane holds no `{name}` object to compare"
        );
        assert_eq!(
            held_by_oidc, held_by_admin,
            "the two planes must hold the SAME `{name}` object, not merely equal \
             configuration: the data plane writes into it and the management plane \
             reports out of it"
        );
    }

    // Non-vacuity, OBSERVED: a plane the constructors left unwired reports something
    // else, so the equalities above cannot hold merely because both sides are the same
    // untouched default.
    expected != (probe.on_oidc)(&unwired.oidc) && expected != (probe.on_admin)(&unwired.admin)
}

/// Both plane states as their CONSTRUCTORS leave them under the shipped default config,
/// with nothing installed and nothing shared.
///
/// This is the non-vacuity baseline, and it is BUILT rather than written down: a probe
/// that could not tell the driven value from what these report is proving nothing, and
/// a hand written "shipped default" can agree with the state struct's real default by
/// coincidence and then quietly stop agreeing. The deliberate absences are the point,
/// so nothing here should be wired up to look more like a boot.
async fn unwired_planes(db: &TestDatabase, env: &Env) -> PlanePair {
    let defaults = Config::default();
    let data_store = Store::connect(db.app_url())
        .await
        .expect("the throwaway database accepts the data-plane role");
    let control_store = Store::connect(db.control_url())
        .await
        .expect("the throwaway database accepts the control-plane role");
    let issuer_base = SiteContext::derive(&defaults.server)
        .expect("the shipped default server config derives a site context")
        .base_url();
    let registry = Arc::new(IssuerRegistry::store_backed(
        issuer_base.clone(),
        JwksCacheWindow::clamped(defaults.oidc.jwks_cache_max_age_secs),
        data_store.clone(),
    ));
    let oidc = OidcState::new(
        data_store,
        env.clone(),
        registry,
        &defaults.oidc,
        issuer_base,
    );
    let admin = AdminState::new(control_store, env.clone(), &defaults.admin)
        .expect("the shipped default admin config builds a state");
    PlanePair { oidc, admin }
}

#[test]
fn every_declared_shared_value_has_a_probe() {
    // The subject list is the macro-generated declaration, so a value declared there and
    // left undriven here is a failure rather than an absence.
    let declared: Vec<&str> = SHARED_CONFIG_SECTION_NAMES
        .iter()
        .chain(SHARED_BOOT_INPUT_NAMES.iter())
        .copied()
        .collect();
    assert!(
        !declared.is_empty(),
        "the declaration must yield a non-empty subject list"
    );

    for name in &declared {
        assert!(
            PROBES.iter().any(|probe| probe.name == *name),
            "cross-plane value `{name}` is declared in the shared_plane_inputs! \
             invocation but no probe here drives it across the two planes, so nothing \
             would notice if only one plane received it."
        );
    }
    for probe in PROBES {
        assert!(
            declared.contains(&probe.name),
            "a probe drives `{}`, which is no longer a declared cross-plane value",
            probe.name
        );
    }
    assert_eq!(
        PROBES.len(),
        declared.len(),
        "one probe per declared cross-plane value, no duplicates"
    );
    // The generated lists must agree with each other: every identity subject and every
    // constructor input is one of the boot-resolved values.
    for name in SHARED_OBJECT_NAMES
        .iter()
        .chain(SHARED_DERIVED_NAMES.iter())
    {
        assert!(
            SHARED_BOOT_INPUT_NAMES.contains(name),
            "`{name}` is declared an identity or constructor subject but is not among \
             the boot-resolved values"
        );
    }

    for probe in PROBES {
        // A config SECTION must be driven through the config, because that is the shape
        // of the failure: an operator writes it once and both planes must read it. Every
        // other subject is driven in the base harness config, because its keys sit
        // inside tables that config already opens and TOML admits no second table of the
        // same name.
        let is_section = SHARED_CONFIG_SECTION_NAMES.contains(&probe.name);
        assert_eq!(
            is_section,
            !probe.non_default_toml.is_empty(),
            "`{}` is declared {}, so its probe must {} its own section through TOML",
            probe.name,
            if is_section {
                "a config section"
            } else {
                "a boot-resolved value"
            },
            if is_section { "drive" } else { "NOT drive" }
        );

        // An identity probe is REQUIRED for exactly the object subjects, on BOTH planes.
        // For those, equal configuration is not the contract: one plane writes into the
        // object and the other reads out of it, or the value exposes no bytes to compare.
        let is_object = SHARED_OBJECT_NAMES.contains(&probe.name);
        assert_eq!(
            is_object,
            probe.oidc_object.is_some(),
            "`{}` is declared {}, so its probe must {} an identity reader for the data \
             plane",
            probe.name,
            if is_object {
                "a shared object"
            } else {
                "a plain shared value"
            },
            if is_object { "carry" } else { "NOT carry" }
        );
        assert_eq!(
            probe.oidc_object.is_some(),
            probe.admin_object.is_some(),
            "`{}` must read the object on both planes or on neither",
            probe.name
        );
    }
}

#[tokio::test(flavor = "multi_thread")]
async fn both_planes_receive_the_same_shared_values() {
    let db = TestDatabase::start().await;
    let (env, clock): (Env, Arc<ManualClock>) =
        Env::deterministic(SystemTime::UNIX_EPOCH, 0x000B_0074);
    let unwired = unwired_planes(&db, &env).await;

    // The two runs drive the ladder verdicts the OPPOSITE ways round, so a cross-wiring
    // between them cannot hide behind one shared constant.
    let runs = [
        LadderIntent {
            signup_quarantine: true,
            advanced_recovery: false,
        },
        LadderIntent {
            signup_quarantine: false,
            advanced_recovery: true,
        },
    ];
    // Per probe, in how many runs the driven value was distinguishable from what an
    // unwired plane reports, and the distinct values it was driven to.
    let mut distinguishable: Vec<usize> = vec![0; PROBES.len()];
    let mut driven_values: Vec<BTreeSet<String>> = vec![BTreeSet::new(); PROBES.len()];

    for ladder in runs {
        let fixture = fixture(&db, &env, ladder);
        let wired = boot_both_planes(&fixture).await;
        for (index, probe) in PROBES.iter().enumerate() {
            driven_values[index].insert((probe.expected)(&fixture).to_string());
            if observe_probe(probe, &fixture, &wired, &unwired) {
                distinguishable[index] += 1;
            }
        }
    }

    for (index, probe) in PROBES.iter().enumerate() {
        let name = probe.name;
        // A config section, a shared object and a constructor input are driven the same
        // way in every run, so each must be distinguishable from the unwired baseline in
        // EVERY run.
        let always = SHARED_CONFIG_SECTION_NAMES.contains(&name)
            || SHARED_OBJECT_NAMES.contains(&name)
            || SHARED_DERIVED_NAMES.contains(&name);
        if always {
            assert_eq!(
                distinguishable[index],
                runs.len(),
                "the `{name}` probe must drive a value an UNWIRED plane would not \
                 report, in every run, or an install that never ran would still compare \
                 equal"
            );
        } else {
            // A ladder verdict is deliberately driven OFF in one run, where it does equal
            // what an unwired plane reports. It must still be distinguishable in the run
            // that arms it, and it must have been driven BOTH ways: two runs that agreed
            // would hide a cross-wiring between the two verdicts.
            assert!(
                distinguishable[index] >= 1,
                "the `{name}` verdict is never driven away from what an unwired plane \
                 reports, so no run of it proves anything"
            );
            assert!(
                driven_values[index].len() >= 2,
                "the `{name}` verdict must be driven BOTH ways across the runs; a pair \
                 of verdicts held at one constant hides a cross-wiring between them"
            );
        }
    }

    // Hold the deterministic clock until every observation is done, so nothing above
    // read through a seam that had already been dropped.
    drop(clock);
}

/// The boot path INSTALLS the client-key resolver (issues #25, #126 criterion 4).
///
/// This test exists because of a measurement. `OidcState::new` passes `None` for the
/// resolver, and until this change the shipped binary called exactly that: the only
/// `Some(resolver)` call site in the repository was a test harness. THREE surfaces read
/// `client_key_resolver()` and found nothing -- `private_key_jwt` client authentication,
/// the `jwt-bearer` assertion grant, and `jwks_uri` dynamic client registration -- while
/// their own suites stayed green, because those suites construct the resolver themselves.
///
/// The first two were inert. The third hard-refused with an explicit message, so wiring the
/// resolver CHANGES its behaviour rather than restoring it; see the comment at the wiring
/// site in `main.rs`.
///
/// The unwired plane is the control, and it is what makes this non-vacuous: it is built
/// through `OidcState::new` deliberately, so a version of this assertion that could not
/// tell an installed resolver from an absent one fails here rather than passing quietly.
#[tokio::test]
async fn the_boot_path_installs_the_client_key_resolver() {
    // A TTL that is neither the shipped default (300) nor any other duration this harness
    // sets, so an assertion on it cannot pass by coincidence.
    const CONFIGURED_TTL_SECS: u64 = 1234;

    let db = TestDatabase::start().await;
    let env = Env::system();
    let fixture = fixture(
        &db,
        &env,
        LadderIntent {
            signup_quarantine: true,
            advanced_recovery: true,
        },
    );
    let mut fixture = fixture;
    fixture.config.oidc.client_jwks_ttl_secs = CONFIGURED_TTL_SECS;
    let wired = boot_both_planes(&fixture).await;
    let unwired = unwired_planes(&db, &env).await;

    let resolver = wired.oidc.client_key_resolver().cloned().expect(
        "a booted OIDC plane must hold a client-key resolver, or every jwks_uri client and \
         every jwks_uri assertion issuer resolves to no keys at all",
    );
    // INSTALLED IS NOT ENOUGH. A resolver built with a default TTL instead of the configured
    // one is indistinguishable from a correct one at every other seam, and the value it
    // ignores governs how long a key the client has ROTATED OUT stays trusted -- a silent
    // security misconfiguration, in the same shape as the wiring defect this test exists for.
    assert_eq!(
        resolver.ttl(),
        std::time::Duration::from_secs(CONFIGURED_TTL_SECS),
        "the resolver must be built from oidc.client_jwks_ttl_secs, not from a default"
    );
    assert!(
        unwired.oidc.client_key_resolver().is_none(),
        "the unwired control must NOT hold one, or the assertion above proves nothing"
    );
}
