// SPDX-License-Identifier: MIT OR Apache-2.0
//
// GENERATED from verify-vectors.json by scripts/generate-vectors.mjs. Do not edit.
//
// # Why a .mjs beside the .json
//
// The conformance corpus has to be readable from code that runs in FIVE runtimes,
// including workerd. A JSON import needs either an import attribute or a bundler rule,
// and support for both varies across those runtimes and across bundler versions, so a
// JSON import in the shared checks would make the portability matrix depend on the very
// thing it exists to test. A plain ES module imports identically everywhere.
//
// The JSON stays canonical: it is what the Rust conformance test and the Node suite read,
// and `the generated vectors module matches the json corpus` in verify.test.ts fails if
// this file drifts from it.

export default {
  "$comment": "GENERATED by packages/ironauth-sdk/scripts/generate-vectors.mjs (issue #118). Do not edit by hand: scripts/verify-vectors.sh regenerates this file and fails if it differs. Every verifier snippet and SDK in issue #118 is judged against this one corpus.",
  "now": 1800000000,
  "issuer": "https://issuer.example/t/tnt_vectors/e/env_vectors",
  "audience": "cli_vectors",
  "algorithms": [
    "EdDSA",
    "ES256",
    "RS256"
  ],
  "algorithmsEddsaOnly": [
    "EdDSA"
  ],
  "jwks": {
    "keys": [
      {
        "kty": "OKP",
        "crv": "Ed25519",
        "x": "6DrtHwAr87lao-pqeXmJ52C3cwl5LMyWRxL6kCQeleU",
        "kid": "ed25519-1"
      },
      {
        "kty": "EC",
        "crv": "P-256",
        "x": "m7xOvG92h-OQN-KA6ftI-6pJmxbRsXSfosv7N_aMTfk",
        "y": "cddtFHcRRcW9rTGQQ56sTEgYRPBWQqVfzkbob3ZXlT8",
        "kid": "es256-1"
      },
      {
        "kty": "RSA",
        "n": "uRAlOVIju8R1E-j2U0730q3q0lQlJ9aB0l-QPkn-YtryolFz6Sf3BWeSWeHwcpeLpwZQXwil3YCs-eypJcOm15CUCTRDP1Yqqwte7DJxwgg3zZBP7nhaVwnhBiXPkB-Bovaj4ec97Q2sgA5uRU_o_e5tqbOvf6dr2GApFM_M0eS3f7JqVItNgYVeYY6kcZVV1RqVQ6PzNlOSbLKYDgNyzDcItB6x9mZAM2KZoeghUdPo2jV1j9ozV26PGPVsLqWHfkel4SbXkmOdMucr0TXOktfQHcR4viOj4Tjoot1RDa3-fwhWTWLhGN3k8Kku__jlFieltvWfGH_U2nJ-4ygRRQ",
        "e": "AQAB",
        "kid": "rsa-1"
      },
      {
        "kty": "OKP",
        "crv": "Ed25519",
        "x": "HKXZ6AA3cXV3rkGkXABdZYVlYGj74LGGXH7khOzfzzo",
        "kid": "ed25519-decoy"
      }
    ]
  },
  "cases": [
    {
      "name": "valid_eddsa",
      "token": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImVkMjU1MTktMSJ9.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6ImNsaV92ZWN0b3JzIiwic3ViIjoidXNyX3ZlY3RvcnMiLCJpYXQiOjE3OTk5OTk5NDAsIm5iZiI6MTc5OTk5OTk0MCwiZXhwIjoxODAwMDAzNjAwfQ.WSzJV6Zd4bcI8ZfZPvDmgDNQXa8Vji3KEL4VgXYizhVVh8YIlZHuAkbwYprlyQXZ_4MbtFO5c4dZHbYX04nmCQ",
      "expect": "accept",
      "why": "the default posture: an Ed25519 token from the published key, inside its window"
    },
    {
      "name": "valid_es256",
      "token": "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImVzMjU2LTEifQ.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6ImNsaV92ZWN0b3JzIiwic3ViIjoidXNyX3ZlY3RvcnMiLCJpYXQiOjE3OTk5OTk5NDAsIm5iZiI6MTc5OTk5OTk0MCwiZXhwIjoxODAwMDAzNjAwfQ.0WpR5-Q9wSdeRt67tpytwckcQNQ9sdXbE-2f3iDJDpAvrca4pfQv_Bayn9CuhjICC0ntzMFYpLUHvupzK7Lgbw",
      "expect": "accept",
      "why": "the documented interop escape hatch for consumers that cannot verify EdDSA"
    },
    {
      "name": "valid_rs256",
      "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InJzYS0xIn0.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6ImNsaV92ZWN0b3JzIiwic3ViIjoidXNyX3ZlY3RvcnMiLCJpYXQiOjE3OTk5OTk5NDAsIm5iZiI6MTc5OTk5OTk0MCwiZXhwIjoxODAwMDAzNjAwfQ.VFZucc8Tv452TC1iJcHQw2mF-y12ZghVE9N1r2MKuwYsW8WNHYHUbDflBzESvymrk8RnD9zw5CJJyz-TK6TDE6B1S8pIWrpFp5TiltF0X9ruMGH6kfijB-bJ3mUDup_6h_-YmlsATVVGBjn_Rc7j31qe-ecXRReF3YXP7LeSjPdAFxJU_WOn0XLQ0uGLr1Y4G04Z1jPuZfNrqsAtvtBSjiY-jcTp_ApUwuCHpUTWYATGKzm96n9riagyXbIrr5-bqe7qkc4x2NJ_JZAZ57YOBwT8F5kHtetTSzkjcbnO-WyK7tSotYqeW2tib-Aa4f-hERAkz6_CpT7gSfegVkCQcQ",
      "expect": "accept",
      "why": "the one accepted vector BOTH language implementations verify: Rust has no P-256 key type, so ES256 can only ever be an allowlist refusal there, and without this the cross-language agreement would rest on EdDSA alone"
    },
    {
      "name": "valid_audience_array",
      "token": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImVkMjU1MTktMSJ9.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6WyJvdGhlcl9jbGllbnQiLCJjbGlfdmVjdG9ycyJdLCJzdWIiOiJ1c3JfdmVjdG9ycyIsImlhdCI6MTc5OTk5OTk0MCwibmJmIjoxNzk5OTk5OTQwLCJleHAiOjE4MDAwMDM2MDB9.VxCHxEVck1suyukVZiyA_v-owJ0WBEO6j9D2f9Z6lB6xfqD3nSQ87V8BC3vWOaOWwWJwbkTVfPob_htHh8PVDw",
      "expect": "accept",
      "why": "aud may be an array, and membership is what counts (RFC 7519 4.1.3)"
    },
    {
      "name": "valid_at_the_expiry_boundary",
      "token": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImVkMjU1MTktMSJ9.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6ImNsaV92ZWN0b3JzIiwic3ViIjoidXNyX3ZlY3RvcnMiLCJpYXQiOjE3OTk5OTk5NDAsIm5iZiI6MTc5OTk5OTk0MCwiZXhwIjoxODAwMDAwMDAwfQ.dtqexSkHbOhLgFAwrlZzrE_Rx8bX_bmTXnNsgwPWZBckzJXJ6KTXv5IZMwo9jsaChd4QwRQFkkgQ3aqn7xJ8CA",
      "expect": "accept",
      "why": "exp is \"not accepted ON or after\" only once skew is exhausted; at exactly now it is live"
    },
    {
      "name": "alg_none",
      "token": "eyJhbGciOiJub25lIiwidHlwIjoiSldUIiwia2lkIjoiZWQyNTUxOS0xIn0.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6ImNsaV92ZWN0b3JzIiwic3ViIjoidXNyX3ZlY3RvcnMiLCJpYXQiOjE3OTk5OTk5NDAsIm5iZiI6MTc5OTk5OTk0MCwiZXhwIjoxODAwMDAzNjAwfQ.",
      "expect": "algorithm_not_allowed",
      "why": "RFC 8725 3.1: an unsigned token must never verify, and must be refused BEFORE key lookup"
    },
    {
      "name": "alg_not_published_by_the_issuer",
      "token": "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImVzMjU2LTEifQ.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6ImNsaV92ZWN0b3JzIiwic3ViIjoidXNyX3ZlY3RvcnMiLCJpYXQiOjE3OTk5OTk5NDAsIm5iZiI6MTc5OTk5OTk0MCwiZXhwIjoxODAwMDAzNjAwfQ.0WpR5-Q9wSdeRt67tpytwckcQNQ9sdXbE-2f3iDJDpAvrca4pfQv_Bayn9CuhjICC0ntzMFYpLUHvupzK7Lgbw",
      "expect": "algorithm_not_allowed",
      "why": "the SAME token as valid_es256, judged against an issuer publishing EdDSA only: the allow-list is the issuer metadata, never the token header, so a verifier that reads alg from the token accepts this and is wrong"
    },
    {
      "name": "alg_hs256_forged_with_the_public_key",
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImVkMjU1MTktMSJ9.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6ImNsaV92ZWN0b3JzIiwic3ViIjoidXNyX3ZlY3RvcnMiLCJpYXQiOjE3OTk5OTk5NDAsIm5iZiI6MTc5OTk5OTk0MCwiZXhwIjoxODAwMDAzNjAwfQ.Fw8XNVHUN_YoFJszbhX3x0RyxdmEU1k21w7ddDqDx8Y",
      "expect": "algorithm_not_allowed",
      "why": "an asymmetric-only issuer must refuse HS* outright, so the public-key-as-HMAC-secret confusion is inexpressible rather than merely unlikely"
    },
    {
      "name": "tampered_payload",
      "token": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImVkMjU1MTktMSJ9.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6ImNsaV92ZWN0b3JzIiwic3ViIjoidXNyX2FkbWluIiwiaWF0IjoxNzk5OTk5OTQwLCJuYmYiOjE3OTk5OTk5NDAsImV4cCI6MTgwMDAwMzYwMH0.WSzJV6Zd4bcI8ZfZPvDmgDNQXa8Vji3KEL4VgXYizhVVh8YIlZHuAkbwYprlyQXZ_4MbtFO5c4dZHbYX04nmCQ",
      "expect": "bad_signature",
      "why": "the payload was edited under a signature that still parses; only the check catches it"
    },
    {
      "name": "signed_by_an_unpublished_key",
      "token": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImVkMjU1MTktZGVjb3kifQ.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6ImNsaV92ZWN0b3JzIiwic3ViIjoidXNyX3ZlY3RvcnMiLCJpYXQiOjE3OTk5OTk5NDAsIm5iZiI6MTc5OTk5OTk0MCwiZXhwIjoxODAwMDAzNjAwfQ.R3eO5jkfQz9vjlxF-nphJONVjf9lXZBZ9rxqQKeHsZjtbbuZRWzzrSSeCVWOI75AbkXmq-j9ghAJrkEjcDZ0CA",
      "expect": "bad_signature",
      "why": "the named key is published but did not sign this token"
    },
    {
      "name": "unknown_kid",
      "token": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImVkMjU1MTktYWJzZW50In0.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6ImNsaV92ZWN0b3JzIiwic3ViIjoidXNyX3ZlY3RvcnMiLCJpYXQiOjE3OTk5OTk5NDAsIm5iZiI6MTc5OTk5OTk0MCwiZXhwIjoxODAwMDAzNjAwfQ.mOtxDdQAuNUEsqtKMmYdCiSdZuXqo25IqbgBduijJPzxICmltc83fSVFJLRW5eJYQaFI_xcehqKmBFVVT9ocBA",
      "expect": "unknown_key",
      "why": "no published key matches; a verifier may refetch once but must not fall back to a guess"
    },
    {
      "name": "embedded_jwk_key_injection",
      "token": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImVkMjU1MTktMSIsImp3ayI6eyJrdHkiOiJPS1AiLCJjcnYiOiJFZDI1NTE5IiwieCI6IkY4M1NFbVNWZ0tNQkxZQ29aZkNQREhWR0RHVm9YVmZ5eFJac0duUFBZUUUifX0.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6ImNsaV92ZWN0b3JzIiwic3ViIjoidXNyX2FkbWluIiwiaWF0IjoxNzk5OTk5OTQwLCJuYmYiOjE3OTk5OTk5NDAsImV4cCI6MTgwMDAwMzYwMH0.a_pz5IZCogJHY2KnYbKEJEe5L1hJBf-gZ-Zbmx06MrIbY_jcF0zb0xzDzisnG3AedT-Yor1Lz7nKxi6c1MlQBA",
      "expect": "bad_signature",
      "why": "the header carries the attacker key that signed it while naming a published kid: a verifier trusting the embedded jwk accepts a token minted by anyone, which is the single most damaging JOSE implementation error there is"
    },
    {
      "name": "unknown_crit_header",
      "token": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImVkMjU1MTktMSIsImNyaXQiOlsiaXJvbmF1dGgtbm90LWEtcmVhbC1leHRlbnNpb24iXX0.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6ImNsaV92ZWN0b3JzIiwic3ViIjoidXNyX3ZlY3RvcnMiLCJpYXQiOjE3OTk5OTk5NDAsIm5iZiI6MTc5OTk5OTk0MCwiZXhwIjoxODAwMDAzNjAwfQ.T-JvZub20KGdmVuCUaFpkAc3Tjl5HdZmfM2Rl4YETenwCi9mFhUVVmDJMWDnv5VEANzqVdhd-eEc5v39OkDFBw",
      "expect": "malformed",
      "why": "RFC 7515 4.1.11: an unrecognised `crit` extension must be refused, never ignored"
    },
    {
      "name": "wrong_issuer",
      "token": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImVkMjU1MTktMSJ9.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfb3RoZXIiLCJhdWQiOiJjbGlfdmVjdG9ycyIsInN1YiI6InVzcl92ZWN0b3JzIiwiaWF0IjoxNzk5OTk5OTQwLCJuYmYiOjE3OTk5OTk5NDAsImV4cCI6MTgwMDAwMzYwMH0.093vZcZI0Br3M0M5XFupdwuqcf7a-BJjW0175vUXxxWbsi_7F5b47MVOybDfReziG5gPwK1eOTdKjB7sHtGdCA",
      "expect": "wrong_issuer",
      "why": "a sibling environment under the same host: iss is compared EXACTLY, never by prefix, or one environment tokens would be accepted as another"
    },
    {
      "name": "wrong_audience",
      "token": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImVkMjU1MTktMSJ9.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6ImFub3RoZXJfY2xpZW50Iiwic3ViIjoidXNyX3ZlY3RvcnMiLCJpYXQiOjE3OTk5OTk5NDAsIm5iZiI6MTc5OTk5OTk0MCwiZXhwIjoxODAwMDAzNjAwfQ.ck0B7Jb9_6fyLQ6Ku0ehivD6PekCiRhMhnPfRq-g1Ld3xDtMoQBI_ve5zPasefxX3Xl5cQa5Dj67giR5Wxf5Dg",
      "expect": "wrong_audience",
      "why": "a token minted for a different client of the SAME issuer must not verify here"
    },
    {
      "name": "expired",
      "token": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImVkMjU1MTktMSJ9.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6ImNsaV92ZWN0b3JzIiwic3ViIjoidXNyX3ZlY3RvcnMiLCJpYXQiOjE3OTk5OTk5NDAsIm5iZiI6MTc5OTk5OTk0MCwiZXhwIjoxNzk5OTk2NDAwfQ.bgZlYhnnai5U-Gn-Tyst8r3rDpa1GSw1CRzFdyYNFxy_isMb-rCrs0L7H2QmllD2nTkbIUeejB3pV46penNuDw",
      "expect": "expired",
      "why": "an hour past expiry, far beyond any sane skew"
    },
    {
      "name": "not_yet_valid",
      "token": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImVkMjU1MTktMSJ9.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlL3QvdG50X3ZlY3RvcnMvZS9lbnZfdmVjdG9ycyIsImF1ZCI6ImNsaV92ZWN0b3JzIiwic3ViIjoidXNyX3ZlY3RvcnMiLCJpYXQiOjE3OTk5OTk5NDAsIm5iZiI6MTgwMDAwMzYwMCwiZXhwIjoxODAwMDAzNjAwfQ.LFyLhp9CwAowbUbdmafYAJ2pIs5fgj_vd5cKA-S_UmE3fBcNZ8Ue9-qEsSvI9QEtmRQ_TqxedWQMLQbh05zSAQ",
      "expect": "not_yet_valid",
      "why": "nbf an hour in the future, so a verifier ignoring nbf is caught"
    },
    {
      "name": "malformed_two_segments",
      "token": "aaaa.bbbb",
      "expect": "malformed",
      "why": "a JWS has three segments"
    },
    {
      "name": "malformed_not_base64",
      "token": "!!!.!!!.!!!",
      "expect": "malformed",
      "why": "segments that do not decode must be refused before anything else is attempted"
    }
  ]
};
