// SPDX-License-Identifier: MIT OR Apache-2.0

/**
 * The JWT debugger's diagnoses, against the SHARED conformance corpus (issue #123 criterion 3).
 *
 * > The JWT debugger correctly diagnoses at least: valid token, expired, wrong issuer, unknown
 * > kid, and disallowed alg.
 *
 * All five are already vectors in `verify-vectors.json`, so this drives the real corpus rather
 * than five hand-made tokens. That matters for a reason beyond convenience: the corpus is
 * regenerated by a script and gated for freshness, so a token here cannot quietly rot into
 * something that no longer exercises the case its name claims.
 *
 * ## What is asserted, and why it is not just the boolean
 *
 * A debugger that says "invalid" for all four failures would satisfy a valid/invalid assertion
 * completely while being useless. So each case asserts the REASON and that the human-facing
 * sentence names the thing that is actually wrong -- the algorithm, the kid, the issuer -- which
 * is the difference between a tool that ends the debugging session and one that starts it.
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

import { diagnose } from './debug.js';
import { JwksCache } from './verify.js';

interface Corpus {
  now: number;
  issuer: string;
  audience: string;
  algorithms: string[];
  algorithmsEddsaOnly: string[];
  jwks: { keys: JsonWebKey[] };
  cases: Array<{ name: string; token: string; expect: string; why: string }>;
}

const corpus = JSON.parse(
  readFileSync(new URL('../vectors/verify-vectors.json', import.meta.url), 'utf8'),
) as Corpus;

function keys(): JwksCache {
  const send = (async () =>
    new Response(JSON.stringify(corpus.jwks), {
      headers: { 'Content-Type': 'application/json', 'Cache-Control': 'max-age=300' },
    })) as unknown as typeof fetch;
  return new JwksCache({ uri: 'https://issuer.example/jwks', fetch: send, now: () => corpus.now });
}

function tokenOf(name: string): string {
  const entry = corpus.cases.find((c) => c.name === name);
  assert.ok(entry, `the corpus carries ${name}`);
  return entry.token;
}

function optionsFor(name: string) {
  return {
    issuer: corpus.issuer,
    audience: corpus.audience,
    // The one case judged against an EdDSA-only issuer, which is what turns it into a test of
    // the published set rather than of whether ES256 happens to be implemented.
    algorithms: name === 'alg_not_published_by_the_issuer' ? corpus.algorithmsEddsaOnly : corpus.algorithms,
    keys: keys(),
    now: () => corpus.now,
    skewSeconds: 0,
  };
}

test('a valid token is diagnosed valid, with its claims shown', async () => {
  const result = await diagnose(tokenOf('valid_eddsa'), optionsFor('valid_eddsa'));
  assert.equal(result.valid, true);
  assert.equal(result.reason, undefined);
  assert.equal(result.claims?.iss, corpus.issuer);
  assert.match(result.summary, /verifies/);
  // The observations are what a person reads beside the verdict.
  assert.ok(result.observations.some((o) => o.startsWith('alg: EdDSA')), result.observations.join(' | '));
  assert.ok(result.observations.some((o) => o.startsWith('exp: ')), result.observations.join(' | '));
});

test('an expired token is diagnosed expired, and the fix mentions the clock', async () => {
  const result = await diagnose(tokenOf('expired'), optionsFor('expired'));
  assert.equal(result.valid, false);
  assert.equal(result.reason, 'expired');
  assert.match(result.summary, /expired/i);
  // The SECOND most common cause after a genuinely old token, and the one a person cannot see
  // without being told to look.
  assert.match(result.fix ?? '', /clock/i);
});

test('a wrong issuer is diagnosed by naming BOTH issuers', async () => {
  const result = await diagnose(tokenOf('wrong_issuer'), optionsFor('wrong_issuer'));
  assert.equal(result.valid, false);
  assert.equal(result.reason, 'wrong_issuer');
  // Both sides, because "wrong issuer" alone leaves the reader to work out which is which.
  assert.match(result.summary, new RegExp(corpus.issuer.replace(/[/.]/g, '\\$&')));
  assert.match(result.fix ?? '', /environment/i);
});

test('an unknown kid is diagnosed by naming the kid', async () => {
  const result = await diagnose(tokenOf('unknown_kid'), optionsFor('unknown_kid'));
  assert.equal(result.valid, false);
  assert.equal(result.reason, 'unknown_key');
  assert.match(result.summary, /ed25519-absent/);
  assert.match(result.fix ?? '', /rotation|refetch/i);
});

test('a disallowed alg is diagnosed by naming what the issuer DOES publish', async () => {
  const name = 'alg_not_published_by_the_issuer';
  const result = await diagnose(tokenOf(name), optionsFor(name));
  assert.equal(result.valid, false);
  assert.equal(result.reason, 'algorithm_not_allowed');
  // NAMES BOTH SIDES: the algorithm the token used and the set the issuer publishes. Without the
  // second half the reader cannot tell whether their token or their configuration is wrong, and
  // it is usually the configuration.
  assert.match(result.summary, /ES256/);
  assert.match(result.fix ?? '', /EdDSA/);
});

test('the debugger never throws, whatever it is handed', async () => {
  // A debugger that throws on a malformed token fails exactly when it is most needed: malformed
  // is one of the things a person is trying to find out.
  for (const junk of ['', '.', 'not-a-token', 'a.b', 'a.b.c.d', '{}', 'eyJ9.eyJ9.x']) {
    const result = await diagnose(junk, optionsFor('valid_eddsa'));
    assert.equal(result.valid, false, junk);
    assert.ok(result.summary.length > 0, junk);
  }
});

test('the header and claims are shown even when the token is refused', async () => {
  // Withholding the decode until a token verifies would hide the one thing that explains a kid
  // or alg problem -- which is most of what a person opens this tool for.
  const result = await diagnose(tokenOf('unknown_kid'), optionsFor('unknown_kid'));
  assert.equal(result.valid, false);
  assert.equal(result.header?.kid, 'ed25519-absent');
  assert.equal(result.claims?.iss, corpus.issuer);
});

test('every refusal carries a fix, not only a summary', async () => {
  // The criterion asks the debugger to DIAGNOSE. A sentence naming what happened without one
  // naming what to do is half of that, and it is the half that is easy to ship by accident.
  const refusals = corpus.cases.filter((c) => c.expect !== 'accept');
  assert.ok(refusals.length >= 10, `the corpus should carry the refusals: ${refusals.length}`);
  for (const entry of refusals) {
    const result = await diagnose(entry.token, optionsFor(entry.name));
    assert.equal(result.valid, false, entry.name);
    assert.ok((result.fix ?? '').length > 20, `${entry.name} has no actionable fix`);
  }
});
