// SPDX-License-Identifier: MIT OR Apache-2.0

//! The Fastly Compute snippet against the SHARED conformance corpus (issue #118 criterion 1).
//!
//! > Verify snippets for Cloudflare Workers, Fastly Compute (Rust), Lambda@Edge, and plain
//! > WebCrypto each pass a shared conformance test vector set in CI.
//!
//! SHARED means the same file, not the same idea. This reads
//! `packages/ironauth-sdk/vectors/verify-vectors.json` -- the corpus the TypeScript core and the
//! Python reference client are judged against, generated by one script and regenerated by a
//! freshness gate. A Rust copy of the cases would be a second corpus that drifts, and the first
//! time it drifted the two implementations would disagree about which one was wrong.
//!
//! The corpus is loaded with `include_str!`, so a moved or deleted file is a COMPILE error
//! rather than a test that silently runs zero cases.

use ironauth_fastly_verify::{Alg, Policy, VerifyError, verify};
use serde_json::Value;

/// The corpus, at COMPILE time. See the module header for why this is not a runtime read.
const CORPUS: &str = include_str!("../../../packages/ironauth-sdk/vectors/verify-vectors.json");

/// Every case, run against this snippet.
#[test]
fn the_shared_conformance_corpus_passes() {
    let corpus: Value = serde_json::from_str(CORPUS).expect("the corpus parses");
    let jwks = serde_json::to_vec(&corpus["jwks"]).expect("the jwks re-serializes");
    let issuer = corpus["issuer"].as_str().expect("issuer");
    let audience = corpus["audience"].as_str().expect("audience");
    let now = corpus["now"].as_i64().expect("now");
    let published: Vec<Alg> = corpus["algorithms"]
        .as_array()
        .expect("algorithms")
        .iter()
        .map(|name| Alg::parse(name.as_str().expect("a name")).expect("a known algorithm"))
        .collect();
    let eddsa_only: Vec<Alg> = corpus["algorithmsEddsaOnly"]
        .as_array()
        .expect("algorithmsEddsaOnly")
        .iter()
        .map(|name| Alg::parse(name.as_str().expect("a name")).expect("a known algorithm"))
        .collect();

    let cases = corpus["cases"].as_array().expect("cases");
    // A NON-EMPTY CORPUS, asserted. A loader that produced an empty list would make every
    // assertion below vacuous and this test would report the criterion as held.
    assert!(
        cases.len() >= 19,
        "the corpus shrank to {} cases; it is shared, so this is a real change",
        cases.len()
    );

    let mut accepted = 0_usize;
    let mut rejected = 0_usize;
    for case in cases {
        let name = case["name"].as_str().expect("a name");
        let token = case["token"].as_str().expect("a token");
        let expect = case["expect"].as_str().expect("an expectation");
        // ONE CASE PICKS THE NARROWER ALLOW-LIST, which is the whole point of the corpus
        // carrying two: `alg_not_published_by_the_issuer` is a token this snippet CAN verify
        // and must refuse anyway, because the issuer does not publish that algorithm. Judged
        // against the full list it would be accepted and the case would prove nothing.
        let algorithms: &[Alg] = if name == "alg_not_published_by_the_issuer" {
            &eddsa_only
        } else {
            &published
        };
        let policy = Policy {
            algorithms,
            jwks: &jwks,
            issuer,
            audience,
            now_unix_seconds: now,
            // ZERO, not a default. `valid_at_the_expiry_boundary` and `expired` are one second
            // apart in the corpus, so any leeway at all would make them the same case.
            leeway_seconds: 0,
        };
        let outcome = verify(token, &policy);
        let why = case["why"].as_str().unwrap_or("");
        if expect == "accept" {
            let verified = outcome.unwrap_or_else(|error| {
                panic!(
                    "{name} must be accepted, refused as {}\n  why: {why}",
                    error.reason()
                )
            });
            assert_eq!(
                verified.claims["iss"].as_str(),
                Some(issuer),
                "{name} verified but carries the wrong issuer"
            );
            accepted += 1;
        } else {
            // THE REASON, not merely the refusal. The corpus pins one per case and the
            // TypeScript suite asserts it too -- that is what makes the corpus SHARED rather
            // than merely reused. A verifier that refused everything as "malformed" would pass
            // an is_err check against all fourteen negative cases.
            let error = outcome
                .err()
                .unwrap_or_else(|| panic!("{name} must be REFUSED and was accepted\n  why: {why}"));
            assert_eq!(
                error.reason(),
                expect,
                "{name} must be refused as {expect}, got {}\n  why: {why}",
                error.reason()
            );
            rejected += 1;
        }
    }
    // BOTH DIRECTIONS EXERCISED. A corpus that had become all-reject would pass every assertion
    // above against a verifier that refuses everything, which is the failure a conformance suite
    // is least likely to notice on its own.
    assert!(accepted >= 3, "only {accepted} vectors were accepted");
    assert!(rejected >= 10, "only {rejected} vectors were rejected");
}

/// Criterion 6: "Every snippet and SDK rejects tokens whose alg is outside the issuer's
/// published set, covered by negative tests."
///
/// Separate from the corpus run because it asserts the REASON and not merely the refusal. A
/// token refused for a bad signature would satisfy `is_err` while proving nothing about the
/// allow-list, and the allow-list is the control that stops an issuer's ES256 escape hatch from
/// being usable against an environment that publishes only `EdDSA`.
#[test]
fn an_algorithm_the_issuer_does_not_publish_is_refused_before_any_key_is_looked_up() {
    let corpus: Value = serde_json::from_str(CORPUS).expect("the corpus parses");
    let jwks = serde_json::to_vec(&corpus["jwks"]).expect("the jwks re-serializes");
    let cases = corpus["cases"].as_array().expect("cases");
    let valid_es256 = cases
        .iter()
        .find(|case| case["name"] == "valid_es256")
        .expect("the corpus carries a valid ES256 token");
    let token = valid_es256["token"].as_str().expect("a token");

    // It VERIFIES under the full published set. Without this half the refusal below would be
    // satisfied by a token that was broken for some other reason entirely.
    let permissive = Policy {
        algorithms: &[Alg::EdDsa, Alg::Es256, Alg::Rs256],
        jwks: &jwks,
        issuer: corpus["issuer"].as_str().expect("issuer"),
        audience: corpus["audience"].as_str().expect("audience"),
        now_unix_seconds: corpus["now"].as_i64().expect("now"),
        leeway_seconds: 0,
    };
    assert!(
        verify(token, &permissive).is_ok(),
        "the corpus's ES256 token must verify when ES256 is published"
    );

    let eddsa_only = Policy {
        algorithms: &[Alg::EdDsa],
        ..permissive
    };
    assert_eq!(
        verify(token, &eddsa_only).unwrap_err(),
        VerifyError::AlgorithmNotAllowed,
        "the refusal must name the allow-list, not the signature"
    );
}

/// An EMBEDDED KEY IS INERT: the trusted key is used and the signature fails.
///
/// The corpus files `embedded_jwk_key_injection` as `bad_signature`, and this asserts the
/// property that reason encodes -- that the key in the header was never reached for. A test that
/// only checked "refused" would pass against a verifier that read the embedded key, verified
/// happily, and then rejected the token for some unrelated reason.
///
/// The second half is the one that makes it a test of key injection rather than of a broken
/// token: the SAME token, verified against a JWKS that does contain a matching key, is accepted.
/// So the signature itself is fine, and the only thing standing between the attacker and a
/// forged token is that the header's key is never consulted.
#[test]
fn an_embedded_key_is_never_consulted_and_a_crit_header_is_malformed() {
    let corpus: Value = serde_json::from_str(CORPUS).expect("the corpus parses");
    let jwks = serde_json::to_vec(&corpus["jwks"]).expect("the jwks re-serializes");
    let policy = Policy {
        algorithms: &[Alg::EdDsa, Alg::Es256, Alg::Rs256],
        jwks: &jwks,
        issuer: corpus["issuer"].as_str().expect("issuer"),
        audience: corpus["audience"].as_str().expect("audience"),
        now_unix_seconds: corpus["now"].as_i64().expect("now"),
        leeway_seconds: 0,
    };
    for (name, expected) in [
        ("embedded_jwk_key_injection", VerifyError::BadSignature),
        ("unknown_crit_header", VerifyError::Malformed),
    ] {
        let case = corpus["cases"]
            .as_array()
            .expect("cases")
            .iter()
            .find(|case| case["name"] == name)
            .unwrap_or_else(|| panic!("the corpus carries {name}"));
        let token = case["token"].as_str().expect("a token");
        assert_eq!(
            verify(token, &policy).unwrap_err(),
            expected,
            "{name} must be refused as {}",
            expected.reason()
        );
    }
}

/// `alg: none` is refused in every spelling, including the ones a parser might normalize away.
///
/// The corpus carries one. This adds the case variants, because "in any case or whitespace
/// variant" is a claim about a set and a single vector cannot make it.
#[test]
fn alg_none_is_refused_in_every_spelling() {
    use base64::Engine as _;
    use base64::engine::general_purpose::URL_SAFE_NO_PAD;
    let corpus: Value = serde_json::from_str(CORPUS).expect("the corpus parses");
    let jwks = serde_json::to_vec(&corpus["jwks"]).expect("the jwks re-serializes");
    let policy = Policy {
        algorithms: &[Alg::EdDsa, Alg::Es256, Alg::Rs256],
        jwks: &jwks,
        issuer: corpus["issuer"].as_str().expect("issuer"),
        audience: corpus["audience"].as_str().expect("audience"),
        now_unix_seconds: corpus["now"].as_i64().expect("now"),
        leeway_seconds: 0,
    };
    for spelling in ["none", "None", "NONE", " none ", "nOnE"] {
        let header = URL_SAFE_NO_PAD.encode(format!(r#"{{"alg":"{spelling}","typ":"JWT"}}"#));
        let payload = URL_SAFE_NO_PAD.encode(r#"{"iss":"x","aud":"y","exp":9999999999}"#);
        let token = format!("{header}.{payload}.");
        assert_eq!(
            verify(&token, &policy).unwrap_err(),
            VerifyError::AlgorithmNotAllowed,
            "the {spelling:?} spelling of alg:none must be refused"
        );
    }
}
