// SPDX-License-Identifier: MIT OR Apache-2.0

//! Secret signing keys and their public projections.
//!
//! A [`SigningKey`] owns the private key material for one asymmetric algorithm
//! and knows how to hand out its PUBLIC projection two ways: as a [`TrustedKey`]
//! for the one hardened [`crate::verify`] path (so every mint round-trips
//! through the same verifier), and as JWK components for the JWKS builder. The
//! private material lives inside `ring`'s key types, which expose no secret
//! bytes and implement no `Debug`, and [`SigningKey`]'s own `Debug` prints only
//! the kid and algorithm, never key material.
//!
//! HMAC has no key type here on purpose: symmetric client-secret signing takes
//! its key from the client secret at the call site (see [`crate::mint`]), and a
//! [`SigningKey`] can only ever be asymmetric, so an environment key store built
//! from these can never sign `HS*`.
//!
//! Key generation that needs randomness flows through the [`Entropy`] seam:
//! Ed25519 keys are generated by drawing a 32-byte seed from `Entropy` and are
//! therefore reproducible under a fixed test entropy source. ECDSA and RSA keys
//! are LOADED from provisioned PKCS#8 / PKCS#1 material rather than generated
//! here (`ring` cannot generate RSA keys at all, and its ECDSA generation is
//! bound to its own RNG); loading and signing them still touch `ring`'s RNG,
//! which is documented in [`crate::sign`].

use ironauth_env::Entropy;
use ring::signature::{
    ECDSA_P256_SHA256_FIXED_SIGNING, ECDSA_P384_SHA384_FIXED_SIGNING, EcdsaKeyPair, Ed25519KeyPair,
    KeyPair, RsaKeyPair,
};

use crate::policy::{JwsAlgorithm, KeyError, KeyFamily, TrustedKey};
use crate::sign;

/// The number of bytes in an Ed25519 seed (RFC 8032).
const ED25519_SEED_LEN: usize = 32;

/// The minimum RSA modulus length in bytes (2048 bits), matching the floor the
/// verify side (`TrustedKey::rsa`) enforces, so signing cannot mint under a
/// weaker key than the verifier will accept.
const RSA_MIN_MODULUS_BYTES: usize = 256;

/// The private key material for one asymmetric signing key.
///
/// Crate-private: the live `ring` key objects are handed only to the private
/// [`crate::sign`] module, exactly as trusted public material is handed only to
/// the private [`crate::crypto`] module on the verify side.
pub(crate) enum KeyInner {
    /// An Ed25519 signing key (deterministic signatures, no RNG).
    Ed25519(Ed25519KeyPair),
    /// An ECDSA P-256 signing key.
    EcdsaP256(EcdsaKeyPair),
    /// An ECDSA P-384 signing key.
    EcdsaP384(EcdsaKeyPair),
    /// An RSA signing key (boxed: `RsaKeyPair` is far larger than the others).
    Rsa(Box<RsaKeyPair>),
}

/// The public projection of a signing key, as normalized components.
///
/// Crate-private: consumed by [`SigningKey::verifying_key`] to build a
/// [`TrustedKey`] and by the JWKS builder to emit a public JWK.
pub(crate) enum PublicComponents {
    /// Ed25519 public key: the 32-byte `x` coordinate (OKP).
    Okp {
        /// The raw 32-byte Ed25519 public key.
        x: Vec<u8>,
    },
    /// ECDSA public key: the affine `x` and `y` coordinates.
    Ec {
        /// The JOSE curve name (`P-256` or `P-384`).
        crv: &'static str,
        /// The affine `x` coordinate, big-endian.
        x: Vec<u8>,
        /// The affine `y` coordinate, big-endian.
        y: Vec<u8>,
    },
    /// RSA public key: modulus and exponent, big-endian, no leading zeros.
    Rsa {
        /// The modulus `n`.
        n: Vec<u8>,
        /// The public exponent `e`.
        e: Vec<u8>,
    },
}

/// A secret signing key for one asymmetric algorithm, scoped by an optional
/// `kid`.
///
/// Construct one by generating (Ed25519) or loading (ECDSA, RSA) key material,
/// then use it with [`crate::mint`] to sign, [`SigningKey::verifying_key`] to
/// get the matching trusted verification key, and the JWKS builder to publish
/// its public half. The value never prints or serializes its secret material.
pub struct SigningKey {
    kid: Option<String>,
    algorithm: JwsAlgorithm,
    pub(crate) inner: KeyInner,
}

impl SigningKey {
    /// Generate a fresh Ed25519 signing key, drawing its 32-byte seed from the
    /// [`Entropy`] seam.
    ///
    /// Deterministic under a fixed entropy source, so tests can assert the key
    /// (and thus every token it signs) byte for byte.
    ///
    /// # Errors
    ///
    /// [`SigningKeyError::InvalidKeyMaterial`] only if `ring` rejects the seed,
    /// which does not happen for a 32-byte seed and is surfaced for completeness.
    pub fn generate_ed25519(
        kid: Option<String>,
        entropy: &dyn Entropy,
    ) -> Result<Self, SigningKeyError> {
        let mut seed = [0_u8; ED25519_SEED_LEN];
        entropy.fill_bytes(&mut seed);
        Self::ed25519_from_seed(kid, &seed)
    }

    /// Build an Ed25519 signing key from a raw 32-byte seed (RFC 8032).
    ///
    /// The seed is secret; the caller is responsible for having sourced it
    /// safely (from the [`Entropy`] seam, or from provisioned key material).
    ///
    /// # Errors
    ///
    /// [`SigningKeyError::BadSeedLength`] if `seed` is not exactly 32 bytes, or
    /// [`SigningKeyError::InvalidKeyMaterial`] if `ring` rejects it.
    pub fn ed25519_from_seed(kid: Option<String>, seed: &[u8]) -> Result<Self, SigningKeyError> {
        if seed.len() != ED25519_SEED_LEN {
            return Err(SigningKeyError::BadSeedLength {
                expected: ED25519_SEED_LEN,
                actual: seed.len(),
            });
        }
        let key = Ed25519KeyPair::from_seed_unchecked(seed)
            .map_err(|_| SigningKeyError::InvalidKeyMaterial)?;
        Ok(Self {
            kid,
            algorithm: JwsAlgorithm::EdDsa,
            inner: KeyInner::Ed25519(key),
        })
    }

    /// Load an ECDSA P-256 signing key (algorithm `ES256`) from a PKCS#8 v1
    /// document.
    ///
    /// # Errors
    ///
    /// [`SigningKeyError::InvalidKeyMaterial`] if `ring` rejects the PKCS#8.
    pub fn ecdsa_p256_from_pkcs8(
        kid: Option<String>,
        pkcs8: &[u8],
    ) -> Result<Self, SigningKeyError> {
        let key = EcdsaKeyPair::from_pkcs8(
            &ECDSA_P256_SHA256_FIXED_SIGNING,
            pkcs8,
            &sign::secure_random(),
        )
        .map_err(|_| SigningKeyError::InvalidKeyMaterial)?;
        Ok(Self {
            kid,
            algorithm: JwsAlgorithm::Es256,
            inner: KeyInner::EcdsaP256(key),
        })
    }

    /// Load an ECDSA P-384 signing key (algorithm `ES384`) from a PKCS#8 v1
    /// document.
    ///
    /// # Errors
    ///
    /// [`SigningKeyError::InvalidKeyMaterial`] if `ring` rejects the PKCS#8.
    pub fn ecdsa_p384_from_pkcs8(
        kid: Option<String>,
        pkcs8: &[u8],
    ) -> Result<Self, SigningKeyError> {
        let key = EcdsaKeyPair::from_pkcs8(
            &ECDSA_P384_SHA384_FIXED_SIGNING,
            pkcs8,
            &sign::secure_random(),
        )
        .map_err(|_| SigningKeyError::InvalidKeyMaterial)?;
        Ok(Self {
            kid,
            algorithm: JwsAlgorithm::Es384,
            inner: KeyInner::EcdsaP384(key),
        })
    }

    /// Load an RSA signing key from a PKCS#1 `RSAPrivateKey` DER document, bound
    /// to a specific RSA algorithm.
    ///
    /// One RSA key can serve any of `RS256`/`RS384`/`RS512` (PKCS1-v1_5) and
    /// `PS256`/`PS384`/`PS512` (PSS); `algorithm` fixes which one this handle
    /// signs and publishes, so provisioning the same key under two algorithms is
    /// a deliberate two-handle choice, not an ambient capability.
    ///
    /// # Errors
    ///
    /// [`SigningKeyError::AlgorithmNotRsa`] if `algorithm` is not an RSA
    /// algorithm, [`SigningKeyError::RsaKeyTooSmall`] if the modulus is below the
    /// 2048-bit floor the verify side enforces, or
    /// [`SigningKeyError::InvalidKeyMaterial`] if `ring` rejects the DER.
    pub fn rsa_from_pkcs1_der(
        kid: Option<String>,
        algorithm: JwsAlgorithm,
        der: &[u8],
    ) -> Result<Self, SigningKeyError> {
        if algorithm.key_family() != KeyFamily::Rsa {
            return Err(SigningKeyError::AlgorithmNotRsa);
        }
        let key = RsaKeyPair::from_der(der).map_err(|_| SigningKeyError::InvalidKeyMaterial)?;
        // Symmetry with the verify side: reject a sub-2048-bit modulus, fail
        // closed, so a weak key never signs a token the verifier would refuse.
        if key.public().modulus_len() < RSA_MIN_MODULUS_BYTES {
            return Err(SigningKeyError::RsaKeyTooSmall);
        }
        Ok(Self {
            kid,
            algorithm,
            inner: KeyInner::Rsa(Box::new(key)),
        })
    }

    /// The algorithm this key signs and publishes with.
    #[must_use]
    pub fn algorithm(&self) -> JwsAlgorithm {
        self.algorithm
    }

    /// The `kid` this key answers to, if any.
    #[must_use]
    pub fn kid(&self) -> Option<&str> {
        self.kid.as_deref()
    }

    /// The public-key family of this key.
    #[must_use]
    pub fn key_family(&self) -> KeyFamily {
        self.algorithm.key_family()
    }

    /// The matching public verification key, as the one hardened verifier's
    /// [`TrustedKey`].
    ///
    /// This is how a freshly minted token is proven to round-trip through the
    /// single [`crate::verify`] path: sign with the [`SigningKey`], verify with
    /// its [`SigningKey::verifying_key`].
    ///
    /// # Errors
    ///
    /// [`SigningKeyError::MalformedPublicKey`] if the public projection cannot be
    /// turned into a trusted key, which indicates corrupt key material.
    pub fn verifying_key(&self) -> Result<TrustedKey, SigningKeyError> {
        let kid = self.kid.clone();
        // Each supported curve is matched EXPLICITLY: an unknown curve is a hard,
        // fail-closed error, never silently routed to P-384, so a future curve
        // cannot be misprojected.
        let key = match self.public_components()? {
            PublicComponents::Okp { x } => TrustedKey::ed25519(kid, &x),
            PublicComponents::Ec { crv: "P-256", x, y } => TrustedKey::ecdsa_p256(kid, &x, &y),
            PublicComponents::Ec { crv: "P-384", x, y } => TrustedKey::ecdsa_p384(kid, &x, &y),
            PublicComponents::Ec { .. } => return Err(SigningKeyError::MalformedPublicKey),
            PublicComponents::Rsa { n, e } => TrustedKey::rsa(kid, &n, &e),
        };
        key.map_err(SigningKeyError::from)
    }

    /// The public projection of this key as normalized components.
    pub(crate) fn public_components(&self) -> Result<PublicComponents, SigningKeyError> {
        match &self.inner {
            KeyInner::Ed25519(key) => Ok(PublicComponents::Okp {
                x: key.public_key().as_ref().to_vec(),
            }),
            KeyInner::EcdsaP256(key) => ec_components("P-256", 32, key.public_key().as_ref()),
            KeyInner::EcdsaP384(key) => ec_components("P-384", 48, key.public_key().as_ref()),
            KeyInner::Rsa(key) => {
                let (n, e) = parse_rsa_public_der(key.public().as_ref())?;
                Ok(PublicComponents::Rsa { n, e })
            }
        }
    }
}

impl std::fmt::Debug for SigningKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Never render key material: only the non-secret selectors.
        f.debug_struct("SigningKey")
            .field("kid", &self.kid)
            .field("algorithm", &self.algorithm)
            .finish_non_exhaustive()
    }
}

/// Split a SEC1 uncompressed point (`0x04 || x || y`) into affine coordinates.
fn ec_components(
    crv: &'static str,
    coord_len: usize,
    point: &[u8],
) -> Result<PublicComponents, SigningKeyError> {
    let expected = 1 + 2 * coord_len;
    if point.len() != expected || point.first() != Some(&0x04) {
        return Err(SigningKeyError::MalformedPublicKey);
    }
    Ok(PublicComponents::Ec {
        crv,
        x: point[1..=coord_len].to_vec(),
        y: point[1 + coord_len..].to_vec(),
    })
}

/// Parse `SEQUENCE { INTEGER n, INTEGER e }` (a PKCS#1 `RSAPublicKey`) into its
/// big-endian components with any single leading sign byte stripped.
///
/// The input always comes from `ring`'s own public-key encoding, so a parse
/// failure indicates memory corruption rather than untrusted input; it is still
/// handled without panicking.
fn parse_rsa_public_der(der: &[u8]) -> Result<(Vec<u8>, Vec<u8>), SigningKeyError> {
    let mut cursor = DerCursor::new(der);
    cursor.enter_sequence()?;
    let n = cursor.read_integer()?;
    let e = cursor.read_integer()?;
    Ok((n, e))
}

/// A minimal DER reader for exactly the shapes this module parses.
struct DerCursor<'a> {
    bytes: &'a [u8],
    pos: usize,
}

impl<'a> DerCursor<'a> {
    fn new(bytes: &'a [u8]) -> Self {
        Self { bytes, pos: 0 }
    }

    fn take(&mut self, n: usize) -> Result<&'a [u8], SigningKeyError> {
        let end = self
            .pos
            .checked_add(n)
            .ok_or(SigningKeyError::MalformedPublicKey)?;
        let slice = self
            .bytes
            .get(self.pos..end)
            .ok_or(SigningKeyError::MalformedPublicKey)?;
        self.pos = end;
        Ok(slice)
    }

    fn byte(&mut self) -> Result<u8, SigningKeyError> {
        Ok(self.take(1)?[0])
    }

    /// Read a DER length (short or long form) as a `usize`.
    fn read_length(&mut self) -> Result<usize, SigningKeyError> {
        let first = self.byte()?;
        if first & 0x80 == 0 {
            return Ok(first as usize);
        }
        let count = (first & 0x7f) as usize;
        if count == 0 || count > std::mem::size_of::<usize>() {
            return Err(SigningKeyError::MalformedPublicKey);
        }
        let mut len = 0_usize;
        for &b in self.take(count)? {
            len = (len << 8) | b as usize;
        }
        Ok(len)
    }

    /// Consume a `SEQUENCE` tag and its length, leaving the cursor at the body.
    fn enter_sequence(&mut self) -> Result<(), SigningKeyError> {
        if self.byte()? != 0x30 {
            return Err(SigningKeyError::MalformedPublicKey);
        }
        let _len = self.read_length()?;
        Ok(())
    }

    /// Read one `INTEGER`, returning its big-endian bytes with a single leading
    /// zero sign byte stripped.
    fn read_integer(&mut self) -> Result<Vec<u8>, SigningKeyError> {
        if self.byte()? != 0x02 {
            return Err(SigningKeyError::MalformedPublicKey);
        }
        let len = self.read_length()?;
        let raw = self.take(len)?;
        let trimmed = match raw.split_first() {
            Some((0x00, rest)) if !rest.is_empty() => rest,
            _ => raw,
        };
        Ok(trimmed.to_vec())
    }
}

/// A caller-side error constructing a [`SigningKey`].
///
/// Like the verify side's `KeyError`, these describe caller misuse or corrupt
/// provisioned material, not a token outcome, so they are safe to describe and
/// carry no oracle.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[non_exhaustive]
pub enum SigningKeyError {
    /// An Ed25519 seed was not exactly 32 bytes.
    BadSeedLength {
        /// The required length in bytes.
        expected: usize,
        /// The length that was supplied.
        actual: usize,
    },
    /// `ring` rejected the supplied key material (bad PKCS#8, PKCS#1, or seed).
    InvalidKeyMaterial,
    /// An RSA constructor was asked to bind a non-RSA algorithm.
    AlgorithmNotRsa,
    /// The RSA modulus was below the 2048-bit floor the verify side enforces.
    RsaKeyTooSmall,
    /// The key's public projection could not be formed, indicating corrupt
    /// material.
    MalformedPublicKey,
}

impl From<KeyError> for SigningKeyError {
    fn from(_: KeyError) -> Self {
        // A public projection that a `TrustedKey` constructor rejects means the
        // material is corrupt; the specific length mismatch is not actionable.
        SigningKeyError::MalformedPublicKey
    }
}

impl std::fmt::Display for SigningKeyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SigningKeyError::BadSeedLength { expected, actual } => write!(
                f,
                "Ed25519 seed has wrong length: expected {expected}, got {actual}"
            ),
            SigningKeyError::InvalidKeyMaterial => f.write_str("signing key material was rejected"),
            SigningKeyError::AlgorithmNotRsa => {
                f.write_str("an RSA key constructor was given a non-RSA algorithm")
            }
            SigningKeyError::RsaKeyTooSmall => {
                f.write_str("RSA signing key modulus is below the 2048-bit floor")
            }
            SigningKeyError::MalformedPublicKey => {
                f.write_str("signing key has a malformed public projection")
            }
        }
    }
}

impl std::error::Error for SigningKeyError {}
