#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Regenerates docs/COMPATIBILITY.md from cargo metadata. CI runs this script
# and fails if the committed file is stale, so the published matrix can never
# drift from the workspace (the per-artifact version source of truth).
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

cargo metadata --format-version 1 --no-deps | python3 -c '
import json, sys

meta = json.load(sys.stdin)
rows = []
for pkg in sorted(meta["packages"], key=lambda p: p["name"]):
    kinds = {t for target in pkg["targets"] for t in target["kind"]}
    kind = "binary" if "bin" in kinds else "library"
    msrv = pkg.get("rust_version") or "workspace"
    rows.append((pkg["name"], pkg["version"], kind, msrv))

print("# Artifact compatibility matrix")
print()
print("Generated by scripts/compat-matrix.sh; do not edit by hand. Each artifact")
print("releases independently under its own tag (see docs/RELEASING.md). This")
print("table is the authoritative list of artifacts and their versions at HEAD.")
print()
print("| Artifact | Version | Kind | MSRV |")
print("|----------|---------|------|------|")
for name, version, kind, msrv in rows:
    print(f"| {name} | {version} | {kind} | {msrv} |")
' > docs/COMPATIBILITY.md
echo "compat-matrix: docs/COMPATIBILITY.md regenerated"
