#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Regenerates the published config contract from the ironauth-config crate:
# docs/config-schema.json (the JSON Schema editors validate TOML against, via
# taplo / Even Better TOML) and docs/CONFIG.md (the human reference generated
# from the schema descriptions and the feature registry). CI runs this script
# and fails if the committed files are stale, so neither can drift from the
# code (the schema derives from the Config struct itself).
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

cargo run --quiet -p ironauth-config --example config-schema | python3 -c '
import json, sys

doc = json.load(sys.stdin)
schema = doc["schema"]
features = doc["features"]

GENERATED = "Generated by scripts/config-schema.sh; do not edit by hand."

# --- docs/config-schema.json ------------------------------------------------
schema_out = {"$comment": GENERATED}
schema_out.update(schema)
with open("docs/config-schema.json", "w") as fh:
    json.dump(schema_out, fh, indent=2, sort_keys=False)
    fh.write("\n")

# --- docs/CONFIG.md ---------------------------------------------------------
defs = schema.get("$defs", {})

def resolve(node):
    """Follow a $ref one level; schemars emits at most one level here."""
    if "$ref" in node:
        name = node["$ref"].rsplit("/", 1)[-1]
        merged = dict(defs[name])
        for key, value in node.items():
            if key != "$ref":
                merged.setdefault(key, value)
        return merged
    return node

def type_name(node):
    node = resolve(node)
    if "oneOf" in node or "anyOf" in node:
        members = node.get("oneOf", node.get("anyOf", []))
        names = []
        for member in members:
            name = type_name(member)
            if name not in names:
                names.append(name)
        return " or ".join(names)
    t = node.get("type")
    if isinstance(t, list):
        return " or ".join("unset" if x == "null" else pretty_type(x) for x in t)
    if t is None:
        return "table"
    return pretty_type(t)

def pretty_type(t):
    return {"object": "table", "null": "unset"}.get(t, t)

def describe(node):
    text = node.get("description", "").strip()
    # First sentence only; the schema keeps the full text.
    first = text.split("\n\n")[0].replace("\n", " ")
    return first

def default_of(node):
    if "default" not in node:
        return ""
    value = node["default"]
    if value is None:
        return "unset"
    if isinstance(value, (dict, list)) and not value:
        return "empty"
    if isinstance(value, dict):
        return "see fields"
    return f"`{json.dumps(value)}`"

rows = []

def walk(prefix, node):
    node = resolve(node)
    for key in sorted(node.get("properties", {})):
        child = node["properties"][key]
        path = f"{prefix}{key}"
        resolved = resolve(child)
        rows.append((path, type_name(child), default_of(child), describe(child)))
        if "properties" in resolved:
            walk(f"{path}.", resolved)
        extra = resolved.get("additionalProperties")
        if isinstance(extra, dict):
            walk(f"{path}.<name>.", extra)

walk("", schema)

lines = []
lines.append("# IronAuth configuration reference")
lines.append("")
lines.append(f"{GENERATED} Source of truth:")
lines.append("[docs/config-schema.json](config-schema.json), derived from the")
lines.append("`ironauth_config::Config` struct. Config files are TOML; unknown keys abort")
lines.append("startup. Point your editor at the schema for autocomplete and inline")
lines.append("validation (taplo / Even Better TOML: add `#:schema docs/config-schema.json`")
lines.append("at the top of the file, or map it in `.taplo.toml`).")
lines.append("")
lines.append("## Keys")
lines.append("")
lines.append("| Key | Type | Default | Description |")
lines.append("|-----|------|---------|-------------|")
for path, tname, default, desc in rows:
    lines.append(f"| `{path}` | {tname} | {default} | {desc} |")
lines.append("")
lines.append("## Feature maturity ladder")
lines.append("")
lines.append("Entries under `[features]` must name a feature registered in this build.")
lines.append("Experimental features boot only with `ack` equal to the exact version below;")
lines.append("a breaking change bumps the version and invalidates old acks (review the")
lines.append("changelog, then re-ack). Preview features need only `enabled = true`.")
lines.append("Supported features ignore `ack`.")
lines.append("")
lines.append("| Feature | Maturity | Version | Changelog | Description |")
lines.append("|---------|----------|---------|-----------|-------------|")
for feature in sorted(features, key=lambda f: f["name"]):
    name, maturity, doc = feature["name"], feature["maturity"], feature["doc"]
    version = feature["version"] or ""
    changelog = feature["changelog"] or ""
    lines.append(f"| `{name}` | {maturity} | {version} | {changelog} | {doc} |")
lines.append("")

with open("docs/CONFIG.md", "w") as fh:
    fh.write("\n".join(lines))
'
echo "config-schema: docs/config-schema.json and docs/CONFIG.md regenerated"
