#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Regenerates the published connector contract from the ironauth-connector crate:
# docs/connector-schema.json (the JSON Schema for a ConnectorDefinition) and
# docs/capability-matrix.schema.json (the JSON Schema for the CapabilityMatrix,
# the schema-stability contract issue #75 pins). CI runs this script and fails if
# either committed file is stale, so neither can drift from the code (both schemas
# derive from the crate's types themselves). Idempotent, exactly like
# scripts/config-schema.sh.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

cargo run --quiet -p ironauth-connector --example connector-schema | python3 -c '
import json, sys

doc = json.load(sys.stdin)

GENERATED = "Generated by scripts/connector-schema.sh; do not edit by hand."

def write(path, schema):
    out = {"$comment": GENERATED}
    out.update(schema)
    with open(path, "w") as fh:
        json.dump(out, fh, indent=2, sort_keys=False)
        fh.write("\n")

write("docs/connector-schema.json", doc["connector"])
write("docs/capability-matrix.schema.json", doc["capability_matrix"])
'
echo "connector-schema: docs/connector-schema.json and docs/capability-matrix.schema.json regenerated"
