#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Generate docs/EVENTS-VS-WEBHOOKS.md (issue #107).

#107 asks for docs recommending the events API over webhooks for data synchronisation,
with a decision table. The guidance is editorial and hand-written; the FACTS it rests on
are read out of the code, because a doc that quotes a cap or a semantic and then drifts
from it is worse than one that says nothing: a reader sizes their consumer against the
number in the doc.

Usage:
    events-vs-webhooks.py            write the document
    events-vs-webhooks.py --check    exit 1 if the committed file is stale
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(
    subprocess.run(
        ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=True
    ).stdout.strip()
)
OUT = ROOT / "docs" / "EVENTS-VS-WEBHOOKS.md"
REPOSITORY = ROOT / "crates" / "ironauth-store" / "src" / "repository.rs"


def membership_cap() -> int:
    match = re.search(r"pub const MEMBERSHIP_DELTA_CAP: usize = (\d+);", REPOSITORY.read_text())
    if not match:
        raise SystemExit("events-vs-webhooks: MEMBERSHIP_DELTA_CAP not found")
    return int(match.group(1))


# The test that actually pins the "never a silent gap" claim this document publishes.
GONE_TEST = "a_cursor_that_aged_out_is_told_so_rather_than_handed_an_empty_page"
GONE_TEST_FILE = ROOT / "crates" / "ironauth-store" / "tests" / "events_cursor_ordering.rs"


def gone_guarantee_is_pinned() -> bool:
    """Whether a TEST still proves an aged-out cursor is told so.

    A first version grepped `repository.rs` for `EventPage::Gone`, which was worthless:
    the string also appears in the enum declaration and in doc comments, so deleting the
    behaviour left the guard green. A probe caught that, and the lesson is the general one
    about text scans, that matching a name proves the name exists and nothing else.

    What backs the claim is the named test, so that is what is checked. If somebody deletes
    it, this document stops publishing a guarantee nothing verifies.
    """
    return GONE_TEST in GONE_TEST_FILE.read_text()


def render() -> str:
    cap = membership_cap()
    if not gone_guarantee_is_pinned():
        raise SystemExit(
            f"events-vs-webhooks: {GONE_TEST} is gone, so nothing proves the 'never a "
            "silent gap' claim this document publishes. Restore the test or stop making "
            "the claim."
        )

    return f"""<!-- GENERATED by scripts/events-vs-webhooks.py. Do not edit by hand. -->

# Events or webhooks

Both surfaces carry the same event vocabulary (see `EVENTS.md`). They differ in who is
responsible when something goes wrong, and that is the whole basis for choosing.

## Use the events API to SYNCHRONISE state

A webhook is a push to an endpoint you operate. If that endpoint is down, slow, or
redeployed at the wrong moment, the delivery is retried on our schedule and eventually
dead-lettered, and the gap is discovered by whatever downstream system was relying on the
data. Under retries the order is not the order things happened in.

The events API inverts every one of those. You poll at your own pace, from a cursor you
control, and a read from any past cursor returns the same events in the same order. Nothing
is lost while you are down, because nothing was being pushed.

### What "ordered" means here, precisely

Two guarantees hold for EVERY event on the feed, and they are the two a synchronising
consumer needs:

- **Completeness.** A cursor never advances past an event that had not committed when you
  read, so a concurrent writer cannot slip an event in behind your cursor. That is delivered
  by a visibility watermark on every read rather than by locking writers, so it holds for
  every producer without exception.

  There is one standing assumption behind that, and it is worth stating rather than leaving
  a reader to infer it from the word "never": the watermark compares a row's transaction id
  against the oldest transaction still running, and those two are read in different widths.
  On any cluster that has not yet run through 2^32 transactions they agree; past that point
  the comparison stops discriminating and the guarantee weakens to replay stability alone.
  No deployment has been near it, and closing it is tracked separately.

  Beyond that, RETENTION is where the exceptions are, and there are two of them, in
  opposite directions. A cursor that has never advanced past the beginning is never told that
  older events were pruned, so it can be handed a silently short feed. And a cursor that HAS
  advanced can be told the feed moved past it when nothing of yours was lost, because the
  sequence is shared across every scope in the database and a gap in it may be somebody
  else's rows rather than your pruned ones. So: poll to the end of the feed and keep the
  cursor you get, rather than holding a beginning cursor across an outage longer than the
  retention window; and treat a `Gone` as "resync", not as "your events were deleted".
- **Replay stability.** The same cursor returns the same events in the same order, on every
  read and across restarts. The order is the feed's sequence, and a sequence is never
  reassigned.

One guarantee does NOT hold for most producers, and it is worth being exact about because it
is easy to assume from the word "ordered":

- **Commit-order equality.** A sequence is allocated when a row is written, not when its
  transaction commits, so two transactions that overlap can land on the feed in the opposite
  order to the order they committed in. Closing that gap costs a per-scope lock held to
  commit, which on the authentication path would serialise sign-in per environment, so it is
  not applied there, and in fact no production producer takes that lock through the
  commit-ordered appender at all. Treat the feed as unordered BETWEEN concurrent writers.

  WHERE the feed is written is inventoried in `docs/design/event-ordering-sites.txt` and kept
  current by `scripts/event-ordering-audit.sh`, so a new producer cannot join the feed
  without showing up in a diff. That inventory deliberately records no per-producer ordering
  class: deciding one needs to know what a producer's CALLERS hold, and an inventory built by
  reading source text does not know that. The guarantees above are the ones to rely on, and
  they are the same for every producer.

If you are reconciling state, completeness and replay stability are what you rely on: read to
the end of the feed and your copy converges regardless of the order two concurrent writes
landed in. If you are inferring causality BETWEEN two events from their feed order, compare
their payloads rather than their positions.

## The decision table

| If you are... | Use | Because |
| --- | --- | --- |
| keeping a copy of users, groups, or memberships in sync | **Events** | Order and completeness are the requirement, and both are yours to verify with a cursor. |
| feeding an external authorization engine | **Events** | A missed tuple is an access-control defect, not a missed notification. |
| reacting in near real time to a single occurrence | **Webhooks** | Push wins on latency, and a lost one-off is recoverable by other means. |
| triggering a side effect that must not run twice | **Webhooks**, with your own idempotency key | Delivery is at-least-once on both surfaces; only you can decide what "already done" means. |
| reconciling after an outage | **Events** | Replay from your last cursor is exactly this, and a webhook backlog is not. |
| building a billing or metering pipeline | **Events** | The numbers have to add up, which means no gaps, which means a cursor. |

## What the feed guarantees, and what it costs

**A cursor is never silently wrong.** A read either returns the next page, or reports that
the cursor has aged out past the retention window, and those are different answers. An
aged-out cursor carries the oldest sequence that still exists, so you reconcile from a known
point. An empty page means only that there is nothing new. If those were collapsed into one
answer, a consumer whose cursor had expired would read "nothing new" and resume from a
position that skipped everything pruned in between, and would never learn it lost anything.

**A membership event carries at most {cap} member ids.** Beyond that it is marked truncated
and reports how many members actually changed, and a truncated event must NOT be applied as
a delta: reconcile the full membership from the management API instead. The type makes this
hard to get wrong on purpose, because a truncated change is a different variant rather than
an array with a flag beside it, so the case cannot be read without being handled.

**The feed can lag behind an unrelated workload.** Events are served only once no
transaction that was open when they were written is still running, which is what stops a
cursor advancing past an event that has not committed yet. That check is instance-wide, so a
long-running query elsewhere on the database delays the feed as surely as a slow writer
would. If you need a bound on that, the bound is the length of your longest transaction.
"""


# A repo-relative path in backticks, as this document cites its sources.
CITED_PATH = re.compile(r"`((?:docs|scripts|crates)/[A-Za-z0-9_./-]+)`")


def check_citations(rendered: str) -> list[str]:
    """Every file this document names must exist.

    A published document that points a reader at `scripts/event-ordering-audit.sh` and
    `docs/design/event-ordering-sites.txt` is making a claim about the repository, and until
    now nothing tied the two together: either file could be deleted or renamed and every gate
    stayed green while the doc went on citing it. That is the same shape as a comment
    describing code that has since moved, except it ships to readers outside the repository.
    """
    return sorted(
        {path for path in CITED_PATH.findall(rendered) if not (ROOT / path).exists()}
    )


def main(argv: list[str]) -> int:
    rendered = render()
    dangling = check_citations(rendered)
    if dangling:
        print(
            "events-vs-webhooks: this document cites files that do not exist: "
            + ", ".join(dangling)
            + ". A published citation to a path nobody kept is worse than no citation, "
            "because a reader will go looking for it.",
            file=sys.stderr,
        )
        return 1
    if len(argv) == 2 and argv[1] == "--check":
        if not OUT.exists() or OUT.read_text() != rendered:
            print(
                f"events-vs-webhooks: {OUT.relative_to(ROOT)} is stale or missing. A fact it "
                "publishes changed in the code. Regenerate with "
                "scripts/events-vs-webhooks.py and commit the result."
            )
            return 1
        print(f"events-vs-webhooks: clean ({OUT.relative_to(ROOT)} matches the code)")
        return 0
    OUT.write_text(rendered)
    print(f"events-vs-webhooks: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
