#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Regenerate the published event catalog (issue #108) from the registry in
# `crates/ironauth-store/src/event_catalog.rs`, which is itself DERIVED from the
# audit action list. Two artifacts:
#
#   docs/events/catalog.json  the machine-readable registry: the shared envelope
#                             schema plus every event type with its payload schema
#                             version and JSON Schema. This is what a SIEM
#                             integrator codes against.
#   docs/EVENTS.md            the browsable catalog, grouped by domain, generated
#                             from the same document so the prose cannot drift from
#                             the schemas.
#
# Nothing here is hand written, which is issue #108's "no hand-maintained event docs
# exist". CI runs this and fails if the committed artifacts drift, so a new event
# type cannot land without appearing in the catalog.
#
# The COMPATIBILITY check rides on the same diff: a payload schema edited without a
# version bump shows up as a changed `payload_schema` under an unchanged
# `payload_schema_version`, in a file a reviewer reads.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

# shellcheck source=scripts/lib/generated-artifact.sh
. scripts/lib/generated-artifact.sh

cargo run --quiet -p ironauth-store --example event-catalog > docs/events/catalog.json

python3 - <<'PY'
import json, pathlib
doc = json.loads(pathlib.Path("docs/events/catalog.json").read_text(encoding="utf-8"))


def example_payload(schema, event_type):
    """A minimal instance of `schema`: every REQUIRED field, and nothing else.

    DERIVED, never hand written. An example typed out beside a generated schema is the
    defect this whole file exists to avoid: the schema stays fresh because it is
    regenerated, the example rots because nobody regenerates prose, and a consumer reading
    both believes the stale one. Deriving it means the example cannot disagree with the
    contract -- if a required field is added, the example grows it in the same commit.

    Only the required fields, because that is the smallest thing a producer may legally
    emit, and it is what a consumer must be able to parse. Optional fields are visible in
    the schema immediately above; showing them here would suggest they are always present,
    which is the exact misreading the omit-don't-sentinel convention guards against.
    """
    properties = schema.get("properties", {})
    example = {}
    for name in schema.get("required", []):
        spec = properties.get(name, {})
        kind = spec.get("type")
        if kind == "array":
            item = spec.get("items", {}).get("type")
            example[name] = [f"{name[:-1] if name.endswith('s') else name}_1"] if item == "string" else []
        elif kind == "boolean":
            example[name] = True
        elif kind == "integer":
            # A real-looking epoch in ms for the time-shaped fields, so a reader does not
            # copy a placeholder that would not round trip.
            example[name] = 1735689600000 if name.endswith("_unix_ms") else 1
        elif kind == "object":
            example[name] = {}
        else:
            example[name] = f"{name}_example"
    return example
types = doc["event_types"]
domains = {}
for entry in types:
    domains.setdefault(entry["domain"], []).append(entry)


lines = [
    "# Event catalog",
    "",
    "Generated by `scripts/event-catalog.sh` from the registry in",
    "`crates/ironauth-store/src/event_catalog.rs`; do not edit by hand.",
    "",
    f"{len(types)} event type(s) across {len(domains)} domain(s), every one of them "
    "emitted by a real producer and carrying a payload contract.",
    "",
    "This is the EVENT vocabulary, which is not the audit vocabulary: an audit action",
    "records what an actor DID (`user.create`), an event records what BECAME TRUE",
    "(`user.created`). A type appears here because something emits it, so the list grows",
    "by writing producers rather than by renaming an existing list.",
    "",
    "## The envelope",
    "",
    "Every event, on the push path and the pull path alike, carries this envelope. A",
    "consumer validates it before looking at the payload, so a malformed envelope is a",
    "transport problem it can report rather than a payload it cannot parse.",
    "",
    "```json",
    json.dumps(doc["envelope_schema"], indent=2),
    "```",
    "",
    "`id` is the deduplication contract: it becomes the `webhook-id` header on the push",
    "path and the ordered event id on the pull path, and it is stable across every retry",
    "of the same delivery.",
    "",
    "## Versioning",
    "",
    "Additive changes extend a version; a breaking change mints a new one. An envelope",
    "declaring a version the registry does not emit is REFUSED rather than validated",
    "against whatever schema is current, so a consumer pinning a version cannot silently",
    "receive a different shape.",
    "",
]
for domain in sorted(domains):
    entries = sorted(domains[domain], key=lambda e: e["type"])
    lines.append(f"## `{domain}` ({len(entries)})")
    lines.append("")
    lines.append("| Type | Payload version |")
    lines.append("|---|---|")
    for entry in entries:
        lines.append(f"| `{entry['type']}` | {entry['payload_schema_version']} |")
    lines.append("")
    for entry in entries:
        lines.append(f"### `{entry['type']}` v{entry['payload_schema_version']}")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(entry["payload_schema"], indent=2))
        lines.append("```")
        lines.append("")
        lines.append("A minimal payload, derived from the schema above: every required")
        lines.append("field and nothing else. Optional fields are OMITTED rather than sent")
        lines.append("as a sentinel, so an absent one means absent.")
        lines.append("")
        lines.append("```json")
        lines.append(
            json.dumps(
                example_payload(entry["payload_schema"], entry["type"]), indent=2
            )
        )
        lines.append("```")
        lines.append("")
pathlib.Path("docs/EVENTS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
PY

echo "event-catalog: docs/events/catalog.json and docs/EVENTS.md regenerated"
require_tracked "event-catalog" docs/events/catalog.json docs/EVENTS.md || exit 1
if ! git diff --exit-code docs/events/catalog.json docs/EVENTS.md >/dev/null 2>&1; then
    echo "event-catalog: the committed catalog is STALE."
    echo "  An event type or a payload schema changed. Review the diff: a payload schema"
    echo "  edited under an UNCHANGED payload_schema_version is a breaking change without a"
    echo "  version bump, which is what this diff exists to surface."
    git --no-pager diff -- docs/events/catalog.json docs/EVENTS.md || true
    exit 1
fi
echo "event-catalog: clean"
