#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Regenerates the golden flow object corpus from the ironauth-oidc crate (issue #84, PR 4):
# docs/flow-golden.json, a committed byte stable set of representative flow objects (one per
# journey per state, on both transports) that LOCKS the rendered flow shape -- the exact node
# set, the deterministic node order, the node groups, and the attached message ids. CI runs
# this script and fails if the committed file is stale (git diff --exit-code), so a breaking
# change to any journey's rendered flow is LOUD in the diff and cannot land silently. New
# journeys or node groups are additive (they add goldens without changing the existing ones).
# Idempotent, exactly like scripts/flow-schema.sh and scripts/connector-schema.sh.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

cargo run --quiet -p ironauth-oidc --example flow-golden | python3 -c '
import json, sys

doc = json.load(sys.stdin)

out = {"$comment": "Generated by scripts/flow-golden.sh; do not edit by hand."}
out.update(doc)

with open("docs/flow-golden.json", "w") as fh:
    json.dump(out, fh, indent=2, sort_keys=False)
    fh.write("\n")
'
echo "flow-golden: docs/flow-golden.json regenerated"
