#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Regenerates the published headless flow contract from the ironauth-oidc crate (issue
# #84): docs/flow-schema.json (the JSON Schema for the flow object every M9 surface and M12
# SDK binds to) and docs/flow-messages.json (the numeric message id registry snapshot that
# LOCKS the id assignments; i18n keys on these ids). CI runs this script and fails if either
# committed file is stale, so neither can drift from the code (both derive from the crate's
# own types and the message registry). Idempotent, exactly like scripts/connector-schema.sh.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

cargo run --quiet -p ironauth-oidc --example flow-schema | python3 -c '
import json, sys

doc = json.load(sys.stdin)

GENERATED = "Generated by scripts/flow-schema.sh; do not edit by hand."

def write(path, payload):
    out = {"$comment": GENERATED}
    out.update(payload)
    with open(path, "w") as fh:
        json.dump(out, fh, indent=2, sort_keys=False)
        fh.write("\n")

write("docs/flow-schema.json", doc["schema"])
write("docs/flow-messages.json", doc["messages"])
'
echo "flow-schema: docs/flow-schema.json and docs/flow-messages.json regenerated"
