#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Generate the Go and Python management SDKs from the published contract (issue #122).

#122's whole thesis is that the contract, not a hand-maintained client, is the thing
customers integrate against: "that converts community SDK authors from reverse-engineers
into first-class implementers, caps the matrix tax for a small team". A generated client is
how that stops being a slogan, because the alternative is two more surfaces that drift from
the spec at different rates.

Generated in-house rather than through openapi-generator, following the pattern
`gen-reference-app-bindings.py` already sets. The tradeoff is deliberate: a Java toolchain
downloaded per CI run to emit a client we would then have to review anyway is a large
dependency for a mechanical transform, and the output here is small enough to read.

What is generated is the CALLING SURFACE: one typed method per operation, path parameters
substituted, query parameters passed through, and the request body sent as JSON. Response
bodies are returned undecoded on purpose (see the module docs in the emitted files).

Usage:
    gen-management-sdks.py            write both SDKs
    gen-management-sdks.py --check    exit 1 if either is stale
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(
    subprocess.run(
        ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=True
    ).stdout.strip()
)
SPEC = ROOT / "docs" / "openapi" / "management.json"
GO_OUT = ROOT / "sdks" / "go" / "management" / "client.gen.go"
PY_OUT = ROOT / "sdks" / "python" / "ironauth_management" / "client_gen.py"

METHODS = ("get", "post", "put", "patch", "delete")


def operations() -> list[dict]:
    """Every operation, with its path parameters, sorted so the output is deterministic."""
    spec = json.loads(SPEC.read_text())
    out = []
    for path, item in (spec.get("paths") or {}).items():
        for method, op in item.items():
            if method not in METHODS:
                continue
            out.append(
                {
                    "id": op["operationId"],
                    "method": method.upper(),
                    "path": path,
                    "params": re.findall(r"\{(\w+)\}", path),
                    "has_body": "requestBody" in op,
                    # Collapsed to ONE line. A spec summary may be several lines, and a
                    # newline inside a generated `//` comment or a docstring produces a file
                    # that does not parse -- which is how the first run of this generator
                    # emitted 226 methods and compiled none of them.
                    "summary": " ".join(
                        (op.get("summary") or op["operationId"]).split()
                    ).rstrip("."),
                }
            )
    out.sort(key=lambda o: o["id"])
    return out


def go_name(operation_id: str) -> str:
    return operation_id[0].upper() + operation_id[1:]


def snake(operation_id: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", operation_id).lower()


def render_go(ops: list[dict]) -> str:
    lines = [
        "// Code generated by scripts/gen-management-sdks.py. DO NOT EDIT.",
        "// SPDX-License-Identifier: MIT OR Apache-2.0",
        "",
        "// Package management is a generated client for the IronAuth management API.",
        "//",
        "// It is generated from docs/openapi/management.json, so it cannot describe an",
        "// endpoint the server does not serve. Response bodies are returned as",
        "// *http.Response rather than decoded into generated structs: the contract's error",
        "// taxonomy is stable but its success payloads carry free-form JSON in several",
        "// places, and a generated struct that silently drops an unmodelled field is worse",
        "// than handing the caller the body.",
        "package management",
        "",
        "import (",
        '\t"bytes"',
        '\t"encoding/json"',
        '\t"fmt"',
        '\t"net/http"',
        '\t"net/url"',
        '\t"strings"',
        ")",
        "",
        "// Client calls the management API.",
        "type Client struct {",
        "\tBaseURL string",
        "\tToken   string",
        "\tHTTP    *http.Client",
        "}",
        "",
        "// New returns a client for baseURL authenticating with a management token.",
        "func New(baseURL, token string) *Client {",
        "\treturn &Client{BaseURL: strings.TrimRight(baseURL, \"/\"), Token: token, HTTP: http.DefaultClient}",
        "}",
        "",
        "// do issues one request. Exported methods below differ only in method, path, and",
        "// whether they carry a body, which is exactly what makes them safe to generate.",
        "func (c *Client) do(method, path string, query url.Values, body any) (*http.Response, error) {",
        "\tvar reader *bytes.Reader",
        "\tif body != nil {",
        "\t\tencoded, err := json.Marshal(body)",
        "\t\tif err != nil {",
        "\t\t\treturn nil, fmt.Errorf(\"encode request body: %w\", err)",
        "\t\t}",
        "\t\treader = bytes.NewReader(encoded)",
        "\t} else {",
        "\t\treader = bytes.NewReader(nil)",
        "\t}",
        "\ttarget := c.BaseURL + path",
        "\tif len(query) > 0 {",
        "\t\ttarget += \"?\" + query.Encode()",
        "\t}",
        "\treq, err := http.NewRequest(method, target, reader)",
        "\tif err != nil {",
        "\t\treturn nil, fmt.Errorf(\"build request: %w\", err)",
        "\t}",
        "\treq.Header.Set(\"Authorization\", \"Bearer \"+c.Token)",
        "\tif body != nil {",
        "\t\treq.Header.Set(\"Content-Type\", \"application/json\")",
        "\t}",
        "\treturn c.HTTP.Do(req)",
        "}",
        "",
        "// escape makes a path parameter safe to interpolate. A tenant id is opaque and",
        "// caller-supplied, so interpolating it raw would let one build a path it should not.",
        "func escape(value string) string { return url.PathEscape(value) }",
        "",
    ]
    for op in ops:
        args = ", ".join(f"{p} string" for p in op["params"])
        sig_args = args + (", " if args else "") + "query url.Values"
        if op["has_body"]:
            sig_args += ", body any"
        path_expr = '"' + op["path"] + '"'
        for p in op["params"]:
            path_expr = path_expr.replace("{" + p + "}", '" + escape(' + p + ') + "')
        path_expr = path_expr.replace(' + ""', "").replace('"" + ', "")
        body_arg = "body" if op["has_body"] else "nil"
        lines += [
            f"// {go_name(op['id'])} performs {op['method']} {op['path']}.",
            f"//",
            f"// {op['summary']}.",
            f"func (c *Client) {go_name(op['id'])}({sig_args}) (*http.Response, error) {{",
            f"\treturn c.do(\"{op['method']}\", {path_expr}, query, {body_arg})",
            "}",
            "",
        ]
    return "\n".join(lines)


def render_python(ops: list[dict]) -> str:
    lines = [
        "# Code generated by scripts/gen-management-sdks.py. DO NOT EDIT.",
        "# SPDX-License-Identifier: MIT OR Apache-2.0",
        '"""A generated client for the IronAuth management API.',
        "",
        "Generated from docs/openapi/management.json, so it cannot describe an endpoint the",
        "server does not serve. Responses are returned undecoded for the same reason as the Go",
        "client: a generated model that silently drops an unmodelled field is worse than",
        "handing the caller the body.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import json",
        "import urllib.parse",
        "import urllib.request",
        "from typing import Any",
        "",
        "",
        "class Client:",
        '    """Calls the management API."""',
        "",
        "    def __init__(self, base_url: str, token: str) -> None:",
        '        self.base_url = base_url.rstrip("/")',
        "        self.token = token",
        "",
        "    def _do(",
        "        self,",
        "        method: str,",
        "        path: str,",
        "        query: dict[str, Any] | None = None,",
        "        body: Any | None = None,",
        "    ) -> tuple[int, bytes]:",
        '        """Issue one request, returning the status and the raw body."""',
        "        target = self.base_url + path",
        "        if query:",
        '            target += "?" + urllib.parse.urlencode(query)',
        "        data = None if body is None else json.dumps(body).encode()",
        "        request = urllib.request.Request(target, data=data, method=method)",
        '        request.add_header("Authorization", f"Bearer {self.token}")',
        "        if data is not None:",
        '            request.add_header("Content-Type", "application/json")',
        "        try:",
        "            with urllib.request.urlopen(request) as response:  # noqa: S310",
        "                return response.status, response.read()",
        "        except urllib.error.HTTPError as error:",
        "            # A 4xx is an ANSWER on this API, not a transport failure: the error",
        "            # taxonomy is part of the contract, so the caller gets the body to branch on.",
        "            return error.code, error.read()",
        "",
    ]
    for op in ops:
        summary = op["summary"].replace('"', "'")
        params = op["params"]
        args = "".join(f", {p}: str" for p in params)
        body_arg = ", body: Any | None = None" if op["has_body"] else ""
        path_expr = 'f"' + op["path"].replace("{", "{urllib.parse.quote(").replace("}", ")}") + '"'
        call_body = "body" if op["has_body"] else "None"
        lines += [
            f"    def {snake(op['id'])}(self{args}, query: dict[str, Any] | None = None{body_arg}) -> tuple[int, bytes]:",
            f'        """{summary}. {op["method"]} {op["path"]}."""',
            f'        return self._do("{op["method"]}", {path_expr}, query, {call_body})',
            "",
        ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    ops = operations()
    go_src, py_src = render_go(ops), render_python(ops)

    if len(argv) == 2 and argv[1] == "--check":
        stale = [
            str(path.relative_to(ROOT))
            for path, want in ((GO_OUT, go_src), (PY_OUT, py_src))
            if not path.exists() or path.read_text() != want
        ]
        if stale:
            print(
                "gen-management-sdks: stale or missing: "
                + ", ".join(stale)
                + "\n  The published contract changed. Regenerate with "
                "scripts/gen-management-sdks.py and commit the result."
            )
            return 1
        print(f"gen-management-sdks: clean ({len(ops)} operations in both SDKs)")
        return 0

    for path, src in ((GO_OUT, go_src), (PY_OUT, py_src)):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(src)
    print(f"gen-management-sdks: wrote {len(ops)} operations to both SDKs")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
