# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Generate the reference app's contract bindings FROM the published flow
# artifacts (issue #85). The standalone TypeScript reference app binds the SAME
# normative contract the server publishes, so the app and the server can never
# diverge on the object shape or the message copy: the app's TypeScript types,
# its schema-derived validation constants, and its id->copy fallback map are all
# GENERATED here from docs/flow-schema.json and docs/flow-messages.json, and a
# freshness gate (scripts/reference-app-bindings.sh) fails CI if the committed
# output drifts from the artifacts.
#
# The emitter deliberately handles ONLY the JSON Schema shapes that
# docs/flow-schema.json actually uses and raises on anything unexpected, so a
# future schema shape that this emitter does not model fails loudly here rather
# than emitting silently wrong TypeScript.
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SCHEMA_PATH = ROOT / "docs" / "flow-schema.json"
MESSAGES_PATH = ROOT / "docs" / "flow-messages.json"
OUT_DIR = ROOT / "packages" / "reference-app" / "src" / "contract"

HEADER = (
    "// SPDX-License-Identifier: MIT OR Apache-2.0\n"
    "//\n"
    "// Generated by scripts/gen-reference-app-bindings.py from the published flow\n"
    "// contract; do not edit by hand. Run scripts/reference-app-bindings.sh to\n"
    "// regenerate. The freshness gate in CI fails if this drifts from the\n"
    "// docs/flow-*.json artifacts, so the app and the server cannot diverge.\n"
)


def prim(t):
    if t in ("integer", "number"):
        return "number"
    if t == "string":
        return "string"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    # A nullable array member of a type union (the issue #87 signup field `enum` hint carries
    # `type: ["array", "null"]` with unconstrained items), modelled as an array of unknown.
    if t == "array":
        return "Array<unknown>"
    raise SystemExit(f"gen-bindings: unmodeled primitive type {t!r}")


def ref_name(node):
    ref = node["$ref"]
    if not ref.startswith("#/$defs/"):
        raise SystemExit(f"gen-bindings: unmodeled $ref {ref!r}")
    return ref[len("#/$defs/"):]


def ts_type(node):
    if "$ref" in node:
        return ref_name(node)
    if "const" in node:
        return json.dumps(node["const"])
    if "oneOf" in node:
        subs = node["oneOf"]
        if all("const" in s for s in subs):
            return " | ".join(json.dumps(s["const"]) for s in subs)
        return " | ".join(object_type(s) for s in subs)
    if "anyOf" in node:
        return " | ".join(ts_type(s) for s in node["anyOf"])
    t = node.get("type")
    if isinstance(t, list):
        return " | ".join(prim(x) for x in t)
    if t == "object":
        if "additionalProperties" in node and "properties" not in node:
            return f"Record<string, {ts_type(node['additionalProperties'])}>"
        return object_type(node)
    if t == "array":
        return f"Array<{ts_type(node['items'])}>"
    if t is not None:
        return prim(t)
    raise SystemExit(f"gen-bindings: unmodeled schema node {node!r}")


def object_type(node):
    props = node.get("properties", {})
    required = set(node.get("required", []))
    fields = []
    for name in props:  # preserve schema property order (deterministic in the artifact)
        optional = "" if name in required else "?"
        fields.append(f"{name}{optional}: {ts_type(props[name])};")
    if not fields:
        return "Record<string, never>"
    return "{ " + " ".join(fields) + " }"


def emit_def(name, node):
    # A named object with its own properties reads best as an interface; every
    # other shape (unions, aliases, records, the tagged NodeAttributes union) is
    # a type alias.
    if node.get("type") == "object" and "properties" in node:
        body = "\n".join(
            f"  {n}{'' if n in set(node.get('required', [])) else '?'}: {ts_type(node['properties'][n])};"
            for n in node["properties"]
        )
        return f"export interface {name} {{\n{body}\n}}\n"
    return f"export type {name} = {ts_type(node)};\n"


def const_list(def_node):
    return [s["const"] for s in def_node["oneOf"]]


def main():
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    messages = json.loads(MESSAGES_PATH.read_text(encoding="utf-8"))
    defs = schema["$defs"]

    # ---- flow.gen.ts: the types plus the schema-derived validation constants ----
    parts = [HEADER, "\n/* eslint-disable */\n"]
    root_name = schema.get("title", "Flow")
    for name in sorted(defs):
        parts.append(emit_def(name, defs[name]))
    parts.append(emit_def(root_name, schema))

    # Validation constants derived from the schema so the runtime validator in
    # validate.ts cannot drift from the contract either.
    node_types = []
    for sub in defs["NodeAttributes"]["oneOf"]:
        node_types.append(sub["properties"]["node_type"]["const"])
    required_flow_keys = list(schema["required"])
    consts = {
        "REQUIRED_FLOW_KEYS": required_flow_keys,
        "KNOWN_NODE_TYPES": node_types,
        "KNOWN_NODE_GROUPS": const_list(defs["NodeGroup"]),
        "KNOWN_STATES": const_list(defs["FlowStateTag"]),
        "KNOWN_JOURNEYS": const_list(defs["Journey"]),
        "KNOWN_INPUT_TYPES": const_list(defs["InputType"]),
    }
    for cname, values in consts.items():
        rendered = ", ".join(json.dumps(v) for v in values)
        parts.append(f"\nexport const {cname} = [{rendered}] as const;\n")
    parts.append(f"\nexport const CONTRACT_VERSION = {json.dumps(messages['contract_version'])};\n")

    (OUT_DIR / "flow.gen.ts").write_text("".join(parts), encoding="utf-8")

    # ---- messages.gen.ts: the numeric id -> default copy fallback (the i18n seam) ----
    ms = sorted(messages["messages"], key=lambda m: m["id"])
    lines = [
        HEADER,
        "\n// The default-locale (en) copy the server publishes, keyed by the stable\n"
        "// numeric message id. A fork localizes by overriding these ids (see\n"
        "// messages.ts); the id, never the text, is the localization key.\n",
        "export const MESSAGE_TEXT: Readonly<Record<number, string>> = {\n",
    ]
    for m in ms:
        lines.append(f"  {m['id']}: {json.dumps(m['text'])},\n")
    lines.append("};\n")
    (OUT_DIR / "messages.gen.ts").write_text("".join(lines), encoding="utf-8")

    print(f"gen-reference-app-bindings: wrote {OUT_DIR}/flow.gen.ts and messages.gen.ts")


if __name__ == "__main__":
    sys.exit(main())
