#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Generate the published MCP authorization conformance page (issue #129).

The page is generated from `docs/conformance/mcp-results.json`, which
`scripts/mcp-conformance.sh` writes by MEASURING each item against a real server.
Nothing here decides an outcome; it only renders what was measured.

That split is the point. A conformance page whose prose is written by hand drifts from
the tests that support it, and the drift is invisible because both look fine on their own.
This repo has hit that exact shape more than once, so the page carries no sentence that is
not derived from a measured row.
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
RESULTS = ROOT / "docs" / "conformance" / "mcp-results.json"
PAGE = ROOT / "docs" / "conformance" / "mcp.md"


# Every run seeds a fresh tenant, environment, client, and user, and binds an ephemeral
# port. Rendering those verbatim would make the committed page differ on every run, so the
# drift check that keeps the page honest would fail for a reason that has nothing to do with
# conformance, and would then be turned off. Normalising keeps the page STABLE and keeps the
# evidence readable: what matters is that the audience was a scoped resource on this issuer,
# not which scope this particular run happened to seed.
NORMALISE = [
    (re.compile(r"\b(ten|env|cli|usr|agt|sva|org|akey|iat)_[A-Za-z0-9_-]+"), r"\1_<id>"),
    (re.compile(r"127\.0\.0\.1:\d+"), "127.0.0.1:<port>"),
    (re.compile(r'"client_id_issued_at":\s*\d+'), '"client_id_issued_at":<time>'),
]


def normalise(evidence: str) -> str:
    """Replace run-specific identifiers with stable placeholders."""
    for pattern, replacement in NORMALISE:
        evidence = pattern.sub(replacement, evidence)
    return evidence


def main() -> int:
    if not RESULTS.exists():
        print(
            "gen-mcp-conformance: no measured results at "
            f"{RESULTS.relative_to(ROOT)}; run scripts/mcp-conformance.sh first",
            file=sys.stderr,
        )
        return 1

    data = json.loads(RESULTS.read_text())
    items = data["items"]
    revision = data["spec_revision"]
    passing = sum(1 for item in items if item["outcome"] == "pass")

    lines = [
        "<!-- SPDX-License-Identifier: MIT OR Apache-2.0 -->",
        "",
        "# MCP authorization conformance",
        "",
        "GENERATED by `scripts/gen-mcp-conformance.py` from",
        "`docs/conformance/mcp-results.json`. Do not edit: run",
        "`scripts/mcp-conformance.sh`, which measures every item below against a real",
        "IronAuth and two real sample MCP resource servers, then regenerates this file.",
        "",
        f"Spec revision pinned: **{revision}**. An item here claims conformance against",
        "that revision and no other; a later revision is a new measurement, not a",
        "reinterpretation of this one.",
        "",
        f"**{passing} of {len(items)} items pass.**",
        "",
        "## What the evidence column is",
        "",
        "The response the measurement actually saw: a status code, a challenge header, a",
        "body. It is recorded verbatim rather than summarised, so an item that passes for",
        "the wrong reason is visible here rather than hidden behind the word `pass`.",
        "",
        "| Item | Requirement | Outcome | Evidence |",
        "|------|-------------|---------|----------|",
    ]
    for item in items:
        evidence = normalise(item["evidence"]).replace("|", "\\|").replace("\n", " ")
        if len(evidence) > 180:
            evidence = evidence[:180] + "..."
        outcome = "pass" if item["outcome"] == "pass" else "**FAIL**"
        lines.append(
            f"| `{item['id']}` {item['title']} | {item['requirement']} | {outcome} | `{evidence}` |"
        )

    lines += [
        "",
        "## What this bundle does not claim",
        "",
        "The items above are what is MEASURED. Anything absent from the table is not",
        "claimed, however plausible: a conformance page that lists a requirement without",
        "an evidence row would be asserting a property nobody checked.",
        "",
    ]
    PAGE.write_text("\n".join(lines))
    print(f"gen-mcp-conformance: wrote {PAGE.relative_to(ROOT)} ({passing}/{len(items)} pass)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
