#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Regenerates the published journey artifact contract from the ironauth-journey crate (issue
# #92): docs/journey-schema.json (the draft 2020-12 JSON Schema for the declarative journey
# document every management surface and importer validates against). CI runs this script and
# fails if the committed file is stale, so it can never drift from the code (it derives from
# the crate's own artifact structs). Idempotent, exactly like scripts/flow-schema.sh.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

cargo run --quiet -p ironauth-journey --example journey-schema | python3 -c '
import json, sys

doc = json.load(sys.stdin)

GENERATED = "Generated by scripts/journey-schema.sh; do not edit by hand."

out = {"$comment": GENERATED}
out.update(doc)
with open("docs/journey-schema.json", "w") as fh:
    json.dump(out, fh, indent=2, sort_keys=False)
    fh.write("\n")
'
echo "journey-schema: docs/journey-schema.json regenerated"
