#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# RFC 9700 conformance freshness lint (issue #38). The RFC 9700 checklist is
# encoded as executable CI invariants in crates/ironauth-oidc/tests/rfc9700.rs and
# mapped to each requirement in docs/conformance/rfc9700-checklist.md. This lint
# binds every mounted OAuth endpoint to that coverage, so a future BCP-relevant
# endpoint cannot ship while the checklist still reads complete:
#
#   1. tests/rfc9700.rs is a registered [[test]] (autotests=false, so an
#      unregistered test file is dead and never runs).
#   2. The endpoint inventory is GENERATED from the live router and diffed against
#      the committed copy, exactly like scripts/compat-matrix.sh: a new .route()
#      makes the committed inventory stale and fails CI until it is regenerated and
#      committed.
#   3. Every generated endpoint is named in the checklist doc (a new endpoint must
#      be mapped to a covering test or an explicit not-applicable reason).
#   4. Every rfc9700_* test the checklist claims actually exists as a function, and
#      every rfc9700_* test that exists is claimed by the checklist (no drift in
#      either direction), exactly like scripts/discovery-scan.sh asserts a single
#      source of truth.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

lib="crates/ironauth-oidc/src/lib.rs"
doc="docs/conformance/rfc9700-checklist.md"
cargo="crates/ironauth-oidc/Cargo.toml"
tests_dir="crates/ironauth-oidc/tests"
inventory="docs/conformance/rfc9700-endpoints.txt"

fail=0

# 1. The conformance suite is a registered test target, else it is dead.
if ! grep -q '^name = "rfc9700"$' "$cargo" || ! grep -q '^path = "tests/rfc9700.rs"$' "$cargo"; then
  echo "rfc9700-scan: tests/rfc9700.rs is not a registered [[test]] in $cargo (autotests=false)"
  fail=1
fi

# 2. Regenerate the endpoint inventory from the live oidc_router and diff it.
python3 - "$lib" "$inventory" <<'PY'
import re, sys
lib, out = sys.argv[1], sys.argv[2]
text = open(lib, encoding="utf-8").read()
start = text.index("pub fn oidc_router")
body = text[start:text.index("\n}\n", start)]
routes = sorted(set(re.findall(r'\.route\(\s*"([^"]+)"', body)))
header = (
    "# RFC 9700 endpoint inventory (generated)\n"
    "#\n"
    "# Generated by scripts/rfc9700-scan.sh from the oidc_router in\n"
    "# crates/ironauth-oidc/src/lib.rs; do not edit by hand. Every path here MUST be\n"
    "# mapped to a covering test (or an explicit not-applicable reason) in\n"
    "# docs/conformance/rfc9700-checklist.md, so a new OAuth endpoint cannot ship\n"
    "# uncovered while the checklist reads complete.\n"
)
open(out, "w", encoding="utf-8").write(header + "\n".join(routes) + "\n")
PY
if ! git diff --exit-code "$inventory" >/dev/null 2>&1; then
  echo "rfc9700-scan: $inventory is stale (a route changed). Regenerated; review and commit it,"
  echo "              and map any new endpoint in $doc."
  git --no-pager diff -- "$inventory" || true
  fail=1
fi

# 3. Every generated endpoint is named in the checklist doc.
while IFS= read -r path; do
  case "$path" in ''|'#'*) continue ;; esac
  if ! grep -qF -- "$path" "$doc"; then
    echo "rfc9700-scan: endpoint '$path' is not mapped in $doc (uncovered endpoint)"
    fail=1
  fi
done < "$inventory"

# 4. The checklist and the suite reference the SAME set of rfc9700_* tests.
#    (a) every rfc9700_* test the doc claims exists as a function;
#    (b) every rfc9700_* test defined in the suite is claimed by the doc.
doc_tests=$(grep -oE 'rfc9700_[a-z0-9_]+' "$doc" | sort -u || true)
src_tests=$(grep -oE 'fn (rfc9700_[a-z0-9_]+)' "$tests_dir"/rfc9700.rs | sed 's/^fn //' | sort -u || true)

for name in $doc_tests; do
  if ! grep -rqE "fn ${name}\b" "$tests_dir"; then
    echo "rfc9700-scan: checklist references test '${name}', which no test defines"
    fail=1
  fi
done

for name in $src_tests; do
  if ! grep -qF -- "$name" "$doc"; then
    echo "rfc9700-scan: test '${name}' exists but is not traced in $doc"
    fail=1
  fi
done

if [ "$fail" -ne 0 ]; then
  exit 1
fi
echo "rfc9700-scan: clean (every mounted endpoint is mapped; checklist and suite agree)"
