#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# RFC 9700 conformance freshness lint (issue #38). The RFC 9700 checklist is
# encoded as executable CI invariants in crates/ironauth-oidc/tests/rfc9700.rs and
# mapped to each requirement in docs/conformance/rfc9700-checklist.md. This lint
# binds every mounted OAuth endpoint to that coverage, so a future BCP-relevant
# endpoint cannot ship while the checklist still reads complete:
#
#   1. tests/rfc9700.rs is a registered [[test]] (autotests=false, so an
#      unregistered test file is dead and never runs).
#   2. The endpoint inventory is GENERATED from EVERY router in the crate (the
#      protocol router, the discovery router, and the issuer/JWKS router; scanning
#      only one of them would leave a whole router's endpoints invisible to this
#      lint) and diffed against the committed copy, exactly like
#      scripts/compat-matrix.sh: a new .route() anywhere under
#      crates/ironauth-oidc/src makes the committed inventory stale and fails CI
#      until it is regenerated and committed.
#   3. Every generated endpoint is named in the checklist doc (a new endpoint must
#      be mapped to a covering test or an explicit not-applicable reason).
#   4. Every rfc9700_* test the checklist claims actually exists as a function, and
#      every rfc9700_* test that exists is claimed by the checklist (no drift in
#      either direction), exactly like scripts/discovery-scan.sh asserts a single
#      source of truth.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

src="crates/ironauth-oidc/src"
doc="docs/conformance/rfc9700-checklist.md"
cargo="crates/ironauth-oidc/Cargo.toml"
tests_dir="crates/ironauth-oidc/tests"
inventory="docs/conformance/rfc9700-endpoints.txt"

fail=0

# 1. The conformance suite is a registered test target, else it is dead.
if ! grep -q '^name = "rfc9700"$' "$cargo" || ! grep -q '^path = "tests/rfc9700.rs"$' "$cargo"; then
  echo "rfc9700-scan: tests/rfc9700.rs is not a registered [[test]] in $cargo (autotests=false)"
  fail=1
fi

# 2. Regenerate the endpoint inventory from EVERY router in the crate and diff it.
#    The inventory is every .route() literal under crates/ironauth-oidc/src, so it
#    is bound to the whole mounted surface (oidc_router, discovery_router, and the
#    issuer/JWKS router) rather than to one function that a new router could bypass.
python3 - "$src" "$inventory" <<'PY'
import pathlib, re, sys
src, out = pathlib.Path(sys.argv[1]), sys.argv[2]
routes = set()
for path in sorted(src.rglob("*.rs")):
    text = path.read_text(encoding="utf-8")
    routes.update(re.findall(r'\.route\(\s*"([^"]+)"', text))
header = (
    "# RFC 9700 endpoint inventory (generated)\n"
    "#\n"
    "# Generated by scripts/rfc9700-scan.sh from EVERY .route() mounted under\n"
    "# crates/ironauth-oidc/src (the protocol router, the discovery router, and the\n"
    "# issuer/JWKS router); do not edit by hand. Every path here MUST be mapped to a\n"
    "# covering test (or an explicit not-applicable reason) in\n"
    "# docs/conformance/rfc9700-checklist.md, so a new OAuth endpoint cannot ship\n"
    "# uncovered while the checklist reads complete.\n"
)
open(out, "w", encoding="utf-8").write(header + "\n".join(sorted(routes)) + "\n")
PY
if ! git diff --exit-code "$inventory" >/dev/null 2>&1; then
  echo "rfc9700-scan: $inventory is stale (a route changed). Regenerated; review and commit it,"
  echo "              and map any new endpoint in $doc."
  git --no-pager diff -- "$inventory" || true
  fail=1
fi

# 3. Every generated endpoint is named in the checklist doc.
while IFS= read -r path; do
  case "$path" in ''|'#'*) continue ;; esac
  if ! grep -qF -- "$path" "$doc"; then
    echo "rfc9700-scan: endpoint '$path' is not mapped in $doc (uncovered endpoint)"
    fail=1
  fi
done < "$inventory"

# 4. The checklist and the suite reference the SAME set of rfc9700_* tests.
#    (a) every rfc9700_* test the doc claims exists as a function;
#    (b) every rfc9700_* test defined in the suite is claimed by the doc.
doc_tests=$(grep -oE 'rfc9700_[a-z0-9_]+' "$doc" | sort -u || true)
src_tests=$(grep -oE 'fn (rfc9700_[a-z0-9_]+)' "$tests_dir"/rfc9700.rs | sed 's/^fn //' | sort -u || true)

for name in $doc_tests; do
  if ! grep -rqE "fn ${name}\b" "$tests_dir"; then
    echo "rfc9700-scan: checklist references test '${name}', which no test defines"
    fail=1
  fi
done

for name in $src_tests; do
  if ! grep -qF -- "$name" "$doc"; then
    echo "rfc9700-scan: test '${name}' exists but is not traced in $doc"
    fail=1
  fi
done

if [ "$fail" -ne 0 ]; then
  exit 1
fi
echo "rfc9700-scan: clean (every mounted endpoint is mapped; checklist and suite agree)"
