#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Generate docs/SDK-CONTRACT.md from the code it describes (issue #122).

#122 asks for the cookie, session, CSRF and error-code formats to be documented as
contract, with a stability policy. Writing that by hand would have been faster and would
have started rotting immediately: the values live in Rust constants and a match statement,
and a prose copy of them is correct exactly until someone renames one.

So every value here is DERIVED:

  * cookie names come from the `*_COOKIE` constants;
  * the error taxonomy comes from the `AuthzErrorCode::as_str` match arms, which the
    compiler forces to be exhaustive, so a new variant cannot be absent from this document
    without the freshness gate noticing;
  * the CSRF rule names the header `same_origin_ok` actually reads.

The prose AROUND those values is hand-written, deliberately: what a value means and what an
SDK may depend on is a decision, not a fact to be scraped. What must never be hand-written
is the value itself, or a count, or a list that claims to be complete.

Usage:
    sdk-contract.py            write docs/SDK-CONTRACT.md
    sdk-contract.py --check    exit 1 if the committed file is stale
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(
    subprocess.run(
        ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=True
    ).stdout.strip()
)
OUT = ROOT / "docs" / "SDK-CONTRACT.md"

# Cookies an SDK can observe. Each is (constant, source file, what it is for). The NAME is
# read from the constant; the description is ours.
COOKIES = [
    ("SESSION_COOKIE", "crates/ironauth-oidc/src/session.rs", "The OP session. An SDK reads its presence, never its contents: the value is opaque and its envelope is not contract."),
    ("OP_BROWSER_STATE_COOKIE", "crates/ironauth-oidc/src/session.rs", "OP browser state for session management (OIDC Session Management 1.0). Not `__Host-` prefixed because the session-management iframe must read it from a sibling origin."),
    ("MAGIC_BINDING_COOKIE", "crates/ironauth-oidc/src/session.rs", "Binds a magic-link click to the browser that requested it, so a forwarded link cannot complete in another browser."),
    ("TRUSTED_DEVICE_COOKIE", "crates/ironauth-oidc/src/session.rs", "Marks a device the user has previously vouched for, so a step-up can be skipped where policy allows."),
]


def read(path: str) -> str:
    return (ROOT / path).read_text()


def cookie_name(constant: str, path: str) -> str:
    match = re.search(rf'{constant}: &str = "([^"]+)"', read(path))
    if not match:
        raise SystemExit(f"sdk-contract: constant {constant} not found in {path}")
    return match.group(1)


def error_codes() -> list[tuple[str, str]]:
    """Every `AuthzErrorCode` and its wire string, from the exhaustive `as_str` match.

    The match is exhaustive because the compiler requires it, which is what makes this a
    complete list rather than a list somebody remembered to update.
    """
    source = read("crates/ironauth-oidc/src/error.rs")
    pairs = re.findall(r'AuthzErrorCode::(\w+) => "([^"]+)"', source)
    if not pairs:
        raise SystemExit("sdk-contract: no AuthzErrorCode arms found; did as_str move?")
    return pairs


def csrf_header() -> str:
    source = read("crates/ironauth-oidc/src/interaction.rs")
    if "SEC_FETCH_SITE" not in source:
        raise SystemExit("sdk-contract: same_origin_ok no longer reads SEC_FETCH_SITE")
    return "Sec-Fetch-Site"


def render() -> str:
    codes = error_codes()
    lines: list[str] = []
    add = lines.append

    add("<!-- GENERATED by scripts/sdk-contract.py. Do not edit by hand. -->")
    add("")
    add("# The IronAuth SDK contract")
    add("")
    add("The wire formats an SDK may depend on, and what it may depend on them FOR.")
    add("")
    add("Every value below is read out of the code that implements it, so this document")
    add("cannot describe a cookie name or an error code the server does not actually use.")
    add("The prose is hand-written; the values are not.")
    add("")
    add("## Stability policy")
    add("")
    add("Three tiers, because \"stable\" without a scope is a promise nobody can keep.")
    add("")
    add("| Tier | What it covers | What we promise |")
    add("| --- | --- | --- |")
    add("| **Contract** | Cookie NAMES, the CSRF rule, error-code wire strings, and the management API surface published in `docs/openapi/management.json` | No breaking change without a major version and one minor release of deprecation notice. Additions are not breaking. |")
    add("| **Observable** | Cookie ATTRIBUTES (`SameSite`, `Max-Age`, `Path`), response ordering, and error `description` text | May change in any release. Depend on the presence of a cookie, never on its attributes; branch on the error CODE, never on its description. |")
    add("| **Internal** | Cookie VALUES and their crypto envelope, session storage, and anything under a path not in the published spec | No promises at all. A value that decodes today may not tomorrow, by design. |")
    add("")
    add("The split is deliberate. An SDK that reads a cookie's *value* has coupled itself to")
    add("a sealing format that exists to be changed when the threat model changes, and")
    add("freezing it would mean choosing SDK convenience over the ability to rotate a")
    add("construction. Reading its *presence* costs nothing and never breaks.")
    add("")
    add("## Cookies")
    add("")
    add("| Name | Purpose |")
    add("| --- | --- |")
    for constant, path, purpose in COOKIES:
        add(f"| `{cookie_name(constant, path)}` | {purpose} |")
    add("")
    add("The `__Host-` prefix is not decoration. It is enforced by the browser: a")
    add("`__Host-` cookie must be `Secure`, must have `Path=/`, and must carry NO `Domain`")
    add("attribute, which makes it unsettable by a sibling subdomain. An SDK that sees the")
    add("prefix can rely on that without asking the server.")
    add("")
    add("## CSRF")
    add("")
    add(f"State-changing interaction endpoints require a same-origin request, decided from")
    add(f"the browser-set `{csrf_header()}` fetch-metadata header rather than from a token an")
    add("SDK would have to fetch and echo.")
    add("")
    add("There is no CSRF token to read, mint, or forward. A cross-site value is refused;")
    add("a same-origin value and an absent header are allowed, because a header the browser")
    add("did not set is not evidence of anything and older browsers omit it. An SDK driving")
    add("these endpoints from a browser needs to do nothing; one driving them from a server")
    add("is not making a cross-site request in the first place.")
    add("")
    add("## Error codes")
    add("")
    add(f"The authorization endpoint's machine-readable codes. {len(codes)} of them, taken")
    add("from the exhaustive match that renders them, so this list cannot fall behind the")
    add("code without the freshness gate failing.")
    add("")
    add("| Code | Rust variant |")
    add("| --- | --- |")
    for variant, wire in sorted(codes, key=lambda pair: pair[1]):
        add(f"| `{wire}` | `AuthzErrorCode::{variant}` |")
    add("")
    add("**Branch on the code, never on the description.** The `description` is prose for a")
    add("human reading a log; it is Observable tier and will change. The code is Contract.")
    add("")
    add("Several of these are deliberately indistinguishable from one another on the wire in")
    add("cases where telling them apart would answer a question the caller has not earned:")
    add("an unknown client and a client presented under the wrong scope are one response, so")
    add("the endpoint is not an oracle for which tenants exist.")
    add("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    rendered = render()
    if len(argv) == 2 and argv[1] == "--check":
        if not OUT.exists():
            print(f"sdk-contract: {OUT.relative_to(ROOT)} is missing; run scripts/sdk-contract.py")
            return 1
        if OUT.read_text() != rendered:
            print(
                f"sdk-contract: {OUT.relative_to(ROOT)} is STALE. A cookie name, the CSRF\n"
                "  header, or an error code changed in the code and the published contract\n"
                "  still describes the old one. Regenerate with scripts/sdk-contract.py and\n"
                "  commit the result."
            )
            return 1
        print(f"sdk-contract: clean ({OUT.relative_to(ROOT)} matches the code)")
        return 0
    OUT.write_text(rendered)
    print(f"sdk-contract: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
