{{- /* SPDX-License-Identifier: MIT OR Apache-2.0 */ -}}
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ironauth.fullname" . }}
  labels:
    {{- include "ironauth.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "ironauth.selectorLabels" . | nindent 6 }}
{{- end }}
