// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Generated by scripts/gen-reference-app-bindings.py from the published flow
// contract; do not edit by hand. Run scripts/reference-app-bindings.sh to
// regenerate. The freshness gate in CI fails if this drifts from the
// docs/flow-*.json artifacts, so the app and the server cannot diverge.

/* eslint-disable */
export type Autocomplete = "username" | "current-password" | "new-password" | "one-time-code" | "webauthn";
export type FlowStateTag = "identifier_password" | "registration_details" | "registration_ack" | "mfa_challenge" | "mfa_enroll" | "recovery_start" | "recovery_ack" | "federation_start" | "completed";
export type InputType = "text" | "password" | "email" | "tel" | "hidden" | "checkbox" | "submit";
export type Journey = "login" | "registration" | "mfa" | "recovery" | "federation";
export interface Message {
  context: MessageContext;
  id: MessageId;
  kind: MessageKind;
  text: string;
}
export type MessageContext = Record<string, string>;
export type MessageId = number;
export type MessageKind = "info" | "success" | "error";
export interface Node {
  attributes: NodeAttributes;
  group: NodeGroup;
  label?: Message | null;
  messages: Array<Message>;
}
export type NodeAttributes = { autocomplete?: Autocomplete | null; disabled: boolean; input_type: InputType; name: string; node_type: "input"; required: boolean; value?: string | null; } | { message: Message; node_type: "text"; };
export type NodeGroup = "default" | "password" | "passkey" | "totp" | "email_otp" | "sms_otp" | "recovery_code" | "oidc" | "profile";
export type Transport = "browser" | "api";
export interface Ui {
  action: string;
  messages: Array<Message>;
  method: string;
  nodes: Array<Node>;
}
export interface Flow {
  contract_version: number;
  expires_at: number;
  id: string;
  journey: Journey;
  request_url?: string | null;
  state: FlowStateTag;
  transport: Transport;
  ui: Ui;
}

export const REQUIRED_FLOW_KEYS = ["contract_version", "id", "journey", "state", "transport", "expires_at", "ui"] as const;

export const KNOWN_NODE_TYPES = ["input", "text"] as const;

export const KNOWN_NODE_GROUPS = ["default", "password", "passkey", "totp", "email_otp", "sms_otp", "recovery_code", "oidc", "profile"] as const;

export const KNOWN_STATES = ["identifier_password", "registration_details", "registration_ack", "mfa_challenge", "mfa_enroll", "recovery_start", "recovery_ack", "federation_start", "completed"] as const;

export const KNOWN_JOURNEYS = ["login", "registration", "mfa", "recovery", "federation"] as const;

export const KNOWN_INPUT_TYPES = ["text", "password", "email", "tel", "hidden", "checkbox", "submit"] as const;

export const CONTRACT_VERSION = 1;
